/*
Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// CE AllReduce local-reduction kernel dispatcher.
//
// ncclCeLocalReduceKernelVec<T, RedOp, U> and its 40 (type, redop)
// instantiations live in one TU each, generated by
// src/device/ce_reduce/generate.py into gensrc/ce_reduce/. This file has no
// device kernels of its own -- it is pure host code that picks the right
// pre-instantiated launcher based on (datatype, op). Splitting the kernels
// out this way lets the build compile/codegen all 40 instantiations in
// parallel instead of paying for them in a single serialized device-link
// pass (two of the 40 -- int8_t/uint8_t Min/Max -- are individually large
// enough that they used to dominate the entire build's wall-clock time).
#include <hip/hip_runtime.h>
#include <stdint.h>

#include "nccl.h"

#define NCCL_CE_DECLARE_TYPE(Type)                                                                    \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Sum(const void*, void*, int, size_t, hipStream_t);  \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Prod(const void*, void*, int, size_t, hipStream_t); \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Min(const void*, void*, int, size_t, hipStream_t);  \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Max(const void*, void*, int, size_t, hipStream_t)

NCCL_CE_DECLARE_TYPE(f32);
NCCL_CE_DECLARE_TYPE(f64);
NCCL_CE_DECLARE_TYPE(f16);
NCCL_CE_DECLARE_TYPE(bf16);
NCCL_CE_DECLARE_TYPE(i32);
NCCL_CE_DECLARE_TYPE(u32);
NCCL_CE_DECLARE_TYPE(i64);
NCCL_CE_DECLARE_TYPE(u64);
NCCL_CE_DECLARE_TYPE(i8);
NCCL_CE_DECLARE_TYPE(u8);

#undef NCCL_CE_DECLARE_TYPE

// *********************************************************************************
// ncclCeLaunchLocalReduce -- host launcher
// *********************************************************************************
ncclResult_t ncclCeLaunchLocalReduce(const void* tmpBuf, void* output, int nRanks, size_t chunkElems,
                                     ncclDataType_t datatype, ncclRedOp_t op, hipStream_t stream) {
  if (chunkElems == 0) return ncclSuccess;

#define NCCL_CE_DISPATCH_REDOP(Type)                                                    \
  do {                                                                                  \
    switch (op) {                                                                       \
    case ncclSum:  return ncclCeLocalReduceLaunch_##Type##_Sum(tmpBuf, output, nRanks, chunkElems, stream);  \
    case ncclProd: return ncclCeLocalReduceLaunch_##Type##_Prod(tmpBuf, output, nRanks, chunkElems, stream); \
    case ncclMin:  return ncclCeLocalReduceLaunch_##Type##_Min(tmpBuf, output, nRanks, chunkElems, stream);  \
    case ncclMax:  return ncclCeLocalReduceLaunch_##Type##_Max(tmpBuf, output, nRanks, chunkElems, stream);  \
    default:       return ncclInvalidArgument;                                          \
    }                                                                                    \
  } while (0)

  switch (datatype) {
  case ncclFloat32:  NCCL_CE_DISPATCH_REDOP(f32);
  case ncclFloat64:  NCCL_CE_DISPATCH_REDOP(f64);
  case ncclFloat16:  NCCL_CE_DISPATCH_REDOP(f16);
  case ncclBfloat16: NCCL_CE_DISPATCH_REDOP(bf16);
  case ncclInt32:    NCCL_CE_DISPATCH_REDOP(i32);
  case ncclUint32:   NCCL_CE_DISPATCH_REDOP(u32);
  case ncclInt64:    NCCL_CE_DISPATCH_REDOP(i64);
  case ncclUint64:   NCCL_CE_DISPATCH_REDOP(u64);
  case ncclInt8:     NCCL_CE_DISPATCH_REDOP(i8);
  case ncclUint8:    NCCL_CE_DISPATCH_REDOP(u8);
  default:
    return ncclInvalidArgument;
  }

#undef NCCL_CE_DISPATCH_REDOP
}
