//! Build script: read the per-CU limits and the arch name out of the
//! rocjitsu presets the builtin agents mirror.
//!
//! These four values and the arch are not mirage's to choose. They
//! describe what the emulator will accept: `cdna5` caps `num_wf_slots`
//! at 64, and rocjitsu refuses a config that asks for more — in
//! `rj_vm_create_from_string`, which means the session dies at daemon
//! start rather than at profile validation, where a user could act on
//! it. So they are read from `configs/*.json` rather than copied into
//! `agents.rs`, and a preset that changes takes the agent with it.
//!
//! They were copied, and they drifted exactly as copies do. `gfx1250.json`
//! became `gfx1250_mi455x.json` with `arch` renamed `cdna5` and its wave
//! slots cut from 80 to 64; the rename reached `agents.rs` and the wave
//! slots did not, so every MI450X session failed at daemon start until
//! somebody read the error and the two files side by side.
//!
//! Read at build time rather than at run time on purpose. The presets are
//! source, not installed data — a released mirage cannot go looking for
//! them — and doing it here means a preset that loses a key fails the
//! build instead of every run.
//!
//! What is deliberately *not* taken from the preset is the shape of the
//! machine: the component tree, the IOD fan-out and the KFD device
//! identity are mirage's own, and all three builtins are a uniform 256
//! CUs where the presets are 320, 288 and 256. See `agents.rs`.

// A build script may panic: a preset that is missing, unparseable, or
// has lost a key is not something the crate can be built without, and
// there is no caller to return an error to.
#![allow(clippy::expect_used, clippy::panic)]

use std::fmt::Write as _;
use std::path::PathBuf;

/// The presets the builtin agents mirror, in `agents()` order: the Rust
/// constant to emit, and the preset it is read from.
const PRESETS: [(&str, &str); 3] = [
    ("MI300X", "gfx942_cdna3"),
    ("MI350X", "gfx950_mi355x"),
    ("MI450X", "gfx1250_mi455x"),
];

/// The per-CU config keys a builtin agent carries. Order is the order
/// they are written into the generated struct literal.
const CU_KEYS: [&str; 4] = [
    "num_wf_slots",
    "sgprs_per_wf",
    "vgprs_per_wf",
    "lds_size_kb",
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let configs = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../rocjitsu/configs");

    let mut out = String::from(
        "// @generated by build.rs from the rocjitsu presets — do not edit.\n\
         // Regenerate by touching the preset or `build.rs`.\n\n",
    );
    for (name, stem) in PRESETS {
        let path = configs.join(format!("{stem}.json"));
        println!("cargo:rerun-if-changed={}", path.display());
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read the rocjitsu preset {}: {e}", path.display()));
        let json: serde_json::Value = serde_json::from_str(&text)
            .unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", path.display()));

        let arch = json
            .pointer("/vm/arch")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("{} has no `vm.arch`", path.display()));
        let cu = first_compute_unit(
            json.pointer("/topology/root")
                .unwrap_or(&serde_json::Value::Null),
        )
        .unwrap_or_else(|| panic!("{} has no `compute_unit` in its topology", path.display()));

        writeln!(
            out,
            "/// Read from `rocjitsu/configs/{stem}.json` at build time.\n\
             pub(crate) const {name}: Preset = Preset {{\n    \
             preset: \"{stem}.json\",\n    arch: \"{arch}\","
        )
        .expect("writing to a String cannot fail");
        for key in CU_KEYS {
            let value = cu_value(cu, key)
                .unwrap_or_else(|| panic!("{} has no `{key}` on its compute unit", path.display()));
            writeln!(out, "    {key}: \"{value}\",").expect("writing to a String cannot fail");
        }
        out.push_str("};\n\n");
    }

    let dest =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR")).join("presets.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// The first `compute_unit` node in a preset's component tree.
///
/// Found by walking rather than by the path `soc -> xcd -> se -> cu`,
/// which differs between presets and would be a second thing to keep in
/// step with them.
fn first_compute_unit(node: &serde_json::Value) -> Option<&serde_json::Value> {
    if node.get("type").and_then(serde_json::Value::as_str) == Some("compute_unit") {
        return Some(node);
    }
    node.get("children")?
        .as_array()?
        .iter()
        .find_map(first_compute_unit)
}

/// One `{"key": …, "value": …}` entry from a component's `config`.
fn cu_value<'a>(node: &'a serde_json::Value, key: &str) -> Option<&'a str> {
    node.get("config")?
        .as_array()?
        .iter()
        .find(|e| e.get("key").and_then(serde_json::Value::as_str) == Some(key))?
        .get("value")?
        .as_str()
}
