// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/operand.h"
#include "rocjitsu/isa/arch/amdgpu/shared/scalar_operand_resolve.h"
#include "rocjitsu/isa/isa_operand_simd_inl.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/register_access.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include <format>
#include <optional>
#include <stdexcept>
#include <string>

namespace rocjitsu {
namespace gfx1250 {

namespace {

struct Packed16VgprSource {
  uint32_t reg = 0;
  uint32_t shift = 0;
};

std::optional<Packed16VgprSource> packed_16bit_vgpr_source(bool packed_16bit_source, int size_bits,
                                                           OperandType opr_type, int ev) {
  if (!packed_16bit_source || size_bits != 16)
    return std::nullopt;
  int selector_base;
  if (opr_type == OperandType::OPR_VGPR)
    selector_base = 0;
  else if (opr_type == OperandType::OPR_SRC)
    selector_base = 256;
  else
    return std::nullopt;
  int selector = ev - selector_base;
  if (selector >= 0 && selector <= 127)
    return Packed16VgprSource{static_cast<uint32_t>(selector), 0};
  if (selector >= 128 && selector <= 255)
    return Packed16VgprSource{static_cast<uint32_t>(selector - 128), 16};
  return std::nullopt;
}

std::optional<Packed16VgprSource> packed_16bit_vgpr_dst(bool packed_16bit_dst, int size_bits,
                                                        OperandType opr_type, int ev) {
  if (!packed_16bit_dst || size_bits != 16 || opr_type != OperandType::OPR_VGPR)
    return std::nullopt;
  if (ev >= 0 && ev <= 127)
    return Packed16VgprSource{static_cast<uint32_t>(ev), 0};
  if (ev >= 128 && ev <= 255)
    return Packed16VgprSource{static_cast<uint32_t>(ev - 128), 16};
  return std::nullopt;
}

} // namespace

namespace {

constexpr int kM0EncodingValue = 125;

bool is_vgpr_only_type(OperandType t) {
  return t == OperandType::OPR_VGPR || t == OperandType::OPR_SRC_VGPR;
}

uint32_t vgpr_index(OperandType opr_type, int ev) {
  if (opr_type == OperandType::OPR_VGPR)
    return static_cast<uint32_t>(ev);
  return static_cast<uint32_t>(ev - 256);
}

uint64_t read_immediate64(OperandType opr_type, int ev) {
  if (opr_type == OperandType::OPR_SIMM32)
    return static_cast<uint64_t>(static_cast<uint32_t>(ev));
  return static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(ev)));
}

} // namespace

// Isa::-scoped SIMD traits — see rocjitsu/isa/isa_operand_simd_inl.h
// for the templated callers in AmdgpuIsaOperand<Isa>.
std::optional<uint32_t> Isa::resolved_vgpr_offset(OperandType opr_type, int ev) {
  if (is_vgpr_only_type(opr_type))
    return vgpr_index(opr_type, ev);
  if (is_immediate_type(opr_type))
    return std::nullopt;
  if (ev >= 256 && ev <= 511)
    return static_cast<uint32_t>(ev - 256);
  return std::nullopt;
}

std::optional<uint32_t> Isa::resolved_vgpr_offset(const amdgpu::Wavefront &wf, OperandType opr_type,
                                                  int ev, amdgpu::VgprMsbRole role) {
  auto off = resolved_vgpr_offset(opr_type, ev);
  if (!off)
    return std::nullopt;
  return *off + (wf.vgpr_msb_for_role(role) << 8);
}

bool Isa::simd_capable_value(OperandType opr_type, int ev) {
  return resolved_vgpr_offset(opr_type, ev).has_value() || is_immediate_type(opr_type) ||
         amdgpu::can_resolve_src_scalar(ev, kM0EncodingValue);
}

uint32_t Isa::simd_broadcast_value(const amdgpu::Wavefront &wf, OperandType opr_type, int ev) {
  return is_immediate_type(opr_type) ? static_cast<uint32_t>(ev)
                                     : amdgpu::resolve_src_scalar(wf, ev, kM0EncodingValue);
}

bool Operand::simd_capable_exec() const {
  if (delegate())
    return delegate()->simd_capable();
  if (packed_16bit_vgpr_source(packed_16bit_source_, size_bits_, opr_type_, encoding_value_))
    return false;
  if (packed_16bit_vgpr_dst(packed_16bit_dst_, size_bits_, opr_type_, encoding_value_))
    return false;
  return Isa::simd_capable_value(opr_type_, encoding_value_);
}

void Operand::read_lane_chunk_exec(const amdgpu::Wavefront &wf, uint32_t lane_base, uint32_t count,
                                   uint32_t *out) const {
  if (delegate()) {
    amdgpu::RegisterAccess(wf).read_chunk(*delegate(), lane_base, count, out);
    return;
  }
  if (packed_16bit_vgpr_source(packed_16bit_source_, size_bits_, opr_type_, encoding_value_)) {
    for (uint32_t i = 0; i < count; ++i)
      out[i] = read_lane_exec(wf, lane_base + i);
    return;
  }
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    uint64_t lane_mask =
        count == 0 ? 0 : util::mask<uint64_t>(static_cast<int>(count)) << lane_base;
    auto region =
        amdgpu::RegisterAccess(wf.cu()).read_vgpr_region(wf.vgpr_alloc().base + voff, 1, lane_mask);
    std::copy_n(region.lanes().begin() + lane_base, count, out);
    return;
  }
  std::fill_n(out, count, Isa::simd_broadcast_value(wf, opr_type_, encoding_value_));
}

void Operand::write_lane_chunk_exec(amdgpu::Wavefront &wf, uint32_t lane_base, uint32_t count,
                                    const uint32_t *vals, uint64_t mask) const {
  if (packed_16bit_vgpr_dst(packed_16bit_dst_, size_bits_, opr_type_, encoding_value_)) {
    for (uint32_t i = 0; i < count; ++i)
      if (mask & (1ULL << i))
        write_lane_exec(wf, lane_base + i, vals[i]);
    return;
  }
  auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this);
  if (!off)
    throw std::logic_error("write_lane_chunk called on non-VGPR operand type");
  uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
  uint32_t reg = wf.vgpr_alloc().base + voff;
  uint64_t full_mask = util::mask<uint64_t>(static_cast<int>(count));
  if ((mask & full_mask) == full_mask) {
    uint8_t *dst = wf.cu().raw_cu().raw_vgpr_data(reg);
    std::memcpy(dst + lane_base * sizeof(uint32_t), vals, count * sizeof(uint32_t));
    return;
  }
  for (uint32_t i = 0; i < count; ++i)
    if (mask & (1ULL << i))
      wf.cu().raw_cu().write_vgpr(reg, lane_base + i, vals[i]);
}

uint32_t Operand::read_scalar_exec(const amdgpu::Wavefront &wf) const {
  if (delegate())
    return amdgpu::RegisterAccess(wf).read_scalar(*delegate());
  // Fieldless operands whose capability policy makes this
  // accessor inert (reads yield a benign 0, writes are no-ops).
  // Driven by the construction-time capability flags applied
  // via apply_fieldless_caps() (see fieldless_policy.py).
  if (!reads_value())
    return 0u;
  if (has_literal64_)
    return static_cast<uint32_t>(literal64_value_);
  if (is_immediate_type(opr_type_))
    return static_cast<uint32_t>(encoding_value_);
  return amdgpu::resolve_src_scalar(wf, encoding_value_, kM0EncodingValue);
}

uint32_t Operand::read_lane_exec(const amdgpu::Wavefront &wf, uint32_t lane) const {
  if (delegate())
    return amdgpu::RegisterAccess(wf).read_lane(*delegate(), lane);
  // Fieldless operands whose capability policy makes this
  // accessor inert (reads yield a benign 0, writes are no-ops).
  // Driven by the construction-time capability flags applied
  // via apply_fieldless_caps() (see fieldless_policy.py).
  if (!reads_value())
    return 0u;
  int ev = encoding_value_;
  if (auto packed = packed_16bit_vgpr_source(packed_16bit_source_, size_bits_, opr_type_, ev)) {
    uint32_t off = packed->reg + (wf.vgpr_msb_for_role(vgpr_msb_role()) << 8);
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, off, false) : off;
    uint8_t byte_mask = packed->shift ? rocjitsu::ExecutionPlugin::kHighHalfByteMask
                                      : rocjitsu::ExecutionPlugin::kLowHalfByteMask;
    uint32_t raw =
        amdgpu::RegisterAccess(wf.cu()).read_vgpr(wf.vgpr_alloc().base + voff, lane, byte_mask);
    return (raw >> packed->shift) & 0xffffu;
  }
  if (auto off = Isa::resolved_vgpr_offset(wf, opr_type_, ev, vgpr_msb_role())) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    return amdgpu::RegisterAccess(wf.cu()).read_vgpr(wf.vgpr_alloc().base + voff, lane);
  }
  if (is_immediate_type(opr_type_))
    return static_cast<uint32_t>(ev);
  if (size_bits_ == 16)
    return amdgpu::resolve_src_scalar16(wf, ev, kM0EncodingValue);
  return amdgpu::resolve_src_scalar(wf, ev, kM0EncodingValue);
}

void Operand::write_scalar_exec(amdgpu::Wavefront &wf, uint32_t val) const {
  // Fieldless operands whose capability policy makes this
  // accessor inert (reads yield a benign 0, writes are no-ops).
  // Driven by the construction-time capability flags applied
  // via apply_fieldless_caps() (see fieldless_policy.py).
  if (!is_writable())
    return;
  amdgpu::resolve_dst_write(wf, encoding_value_, val, kM0EncodingValue);
}

void Operand::write_lane_exec(amdgpu::Wavefront &wf, uint32_t lane, uint32_t val) const {
  // Fieldless operands whose capability policy makes this
  // accessor inert (reads yield a benign 0, writes are no-ops).
  // Driven by the construction-time capability flags applied
  // via apply_fieldless_caps() (see fieldless_policy.py).
  if (!is_writable())
    return;
  if (auto packed =
          packed_16bit_vgpr_dst(packed_16bit_dst_, size_bits_, opr_type_, encoding_value_)) {
    uint32_t off = packed->reg + (wf.vgpr_msb_for_role(vgpr_msb_role()) << 8);
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, off, true) : off;
    uint32_t idx = wf.vgpr_alloc().base + voff;
    uint8_t write_byte_mask = packed->shift ? rocjitsu::ExecutionPlugin::kHighHalfByteMask
                                            : rocjitsu::ExecutionPlugin::kLowHalfByteMask;
    uint32_t placed = (val & 0xffffu) << packed->shift;
    amdgpu::RegisterAccess(wf.cu()).write_vgpr(idx, lane, placed, write_byte_mask);
    return;
  }
  if (auto off = Isa::resolved_vgpr_offset(wf, opr_type_, encoding_value_, vgpr_msb_role())) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    amdgpu::RegisterAccess(wf.cu()).write_vgpr(wf.vgpr_alloc().base + voff, lane, val);
    return;
  }
  throw std::logic_error("write_lane called on non-VGPR operand type");
}

uint64_t Operand::read_lane64_exec(const amdgpu::Wavefront &wf, uint32_t lane) const {
  if (delegate())
    return amdgpu::RegisterAccess(wf).read_lane64(*delegate(), lane);
  // Fieldless operands whose capability policy makes this
  // accessor inert (reads yield a benign 0, writes are no-ops).
  // Driven by the construction-time capability flags applied
  // via apply_fieldless_caps() (see fieldless_policy.py).
  if (!reads_value())
    return 0;
  int ev = encoding_value_;
  if (auto off = Isa::resolved_vgpr_offset(wf, opr_type_, ev, vgpr_msb_role())) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    uint32_t idx = wf.vgpr_alloc().base + voff;
    return amdgpu::RegisterAccess(wf.cu()).read_vgpr64(idx, lane);
  }
  if (has_literal64_)
    return literal64_value_;
  if (is_immediate_type(opr_type_))
    return read_immediate64(opr_type_, ev);
  return amdgpu::resolve_src_scalar64(wf, ev, kM0EncodingValue);
}

void Operand::write_lane64_exec(amdgpu::Wavefront &wf, uint32_t lane, uint64_t val) const {
  // Fieldless operands whose capability policy makes this
  // accessor inert (reads yield a benign 0, writes are no-ops).
  // Driven by the construction-time capability flags applied
  // via apply_fieldless_caps() (see fieldless_policy.py).
  if (!is_writable())
    return;
  if (auto off = Isa::resolved_vgpr_offset(wf, opr_type_, encoding_value_, vgpr_msb_role())) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    uint32_t idx = wf.vgpr_alloc().base + voff;
    amdgpu::RegisterAccess(wf.cu()).write_vgpr64(idx, lane, val);
    return;
  }
  throw std::logic_error("write_lane64 called on non-VGPR operand type");
}

uint64_t Operand::read_scalar64_exec(const amdgpu::Wavefront &wf) const {
  // Fieldless operands whose capability policy makes this
  // accessor inert (reads yield a benign 0, writes are no-ops).
  // Driven by the construction-time capability flags applied
  // via apply_fieldless_caps() (see fieldless_policy.py).
  if (!reads_value())
    return 0;
  if (has_literal64_)
    return literal64_value_;
  if (is_immediate_type(opr_type_))
    return read_immediate64(opr_type_, encoding_value_);
  return amdgpu::resolve_src_scalar64(wf, encoding_value_, kM0EncodingValue);
}

void Operand::write_scalar64_exec(amdgpu::Wavefront &wf, uint64_t val) const {
  // Fieldless operands whose capability policy makes this
  // accessor inert (reads yield a benign 0, writes are no-ops).
  // Driven by the construction-time capability flags applied
  // via apply_fieldless_caps() (see fieldless_policy.py).
  if (!is_writable())
    return;
  amdgpu::resolve_dst_write64(wf, encoding_value_, val);
}

std::optional<uint32_t> Operand::simd_vgpr_base_exec(const amdgpu::Wavefront &wf) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this))
    return wf.vgpr_alloc().base + (wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off);
  return std::nullopt;
}

const amdgpu::VgprStorage *Operand::simd_vgpr_storage_exec(const amdgpu::Wavefront &wf) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    return &wf.cu().raw_cu().template raw_vgpr_reg<64>(wf.vgpr_alloc().base + voff);
  }
  return nullptr;
}

amdgpu::VgprStorage *Operand::simd_vgpr_storage_mut_exec(amdgpu::Wavefront &wf) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    return &wf.cu().raw_cu().template raw_vgpr_reg<64>(wf.vgpr_alloc().base + voff);
  }
  return nullptr;
}

amdgpu::ConstVgprStoragePair64
Operand::simd_vgpr_storage64_exec(const amdgpu::Wavefront &wf) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    uint32_t reg = wf.vgpr_alloc().base + voff;
    return {&wf.cu().raw_cu().template raw_vgpr_reg<64>(reg),
            &wf.cu().raw_cu().template raw_vgpr_reg<64>(reg + 1)};
  }
  return {nullptr, nullptr};
}

amdgpu::VgprStoragePair64 Operand::simd_vgpr_storage64_mut_exec(amdgpu::Wavefront &wf) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    uint32_t reg = wf.vgpr_alloc().base + voff;
    return {&wf.cu().raw_cu().template raw_vgpr_reg<64>(reg),
            &wf.cu().raw_cu().template raw_vgpr_reg<64>(reg + 1)};
  }
  return {nullptr, nullptr};
}

void Operand::simd_notify_read_exec(const amdgpu::Wavefront &wf, uint64_t lane_mask,
                                    uint8_t byte_mask) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    wf.cu().raw_cu().notify_vgpr_read(&wf, wf.vgpr_alloc().base + voff, lane_mask, byte_mask);
  }
}

void Operand::simd_notify_read_mut_exec(amdgpu::Wavefront &wf, uint64_t lane_mask,
                                        uint8_t byte_mask) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    wf.cu().raw_cu().notify_vgpr_read(&wf, wf.vgpr_alloc().base + voff, lane_mask, byte_mask);
  }
}

void Operand::simd_notify_read64_exec(const amdgpu::Wavefront &wf, uint64_t lane_mask,
                                      uint8_t byte_mask) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    uint32_t reg = wf.vgpr_alloc().base + voff;
    wf.cu().raw_cu().notify_vgpr_read(&wf, reg, lane_mask, byte_mask);
    wf.cu().raw_cu().notify_vgpr_read(&wf, reg + 1, lane_mask, byte_mask);
  }
}

void Operand::simd_notify_read64_mut_exec(amdgpu::Wavefront &wf, uint64_t lane_mask,
                                          uint8_t byte_mask) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    uint32_t reg = wf.vgpr_alloc().base + voff;
    wf.cu().raw_cu().notify_vgpr_read(&wf, reg, lane_mask, byte_mask);
    wf.cu().raw_cu().notify_vgpr_read(&wf, reg + 1, lane_mask, byte_mask);
  }
}

void Operand::simd_notify_write_mut_exec(amdgpu::Wavefront &wf, uint64_t lane_mask,
                                         uint8_t byte_mask) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    wf.cu().raw_cu().notify_vgpr_write(&wf, wf.vgpr_alloc().base + voff, lane_mask, byte_mask);
  }
}

void Operand::simd_notify_write64_mut_exec(amdgpu::Wavefront &wf, uint64_t lane_mask,
                                           uint8_t byte_mask) const {
  if (auto off = detail::resolved_vgpr_offset_for_operand<Isa>(wf, *this)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    uint32_t reg = wf.vgpr_alloc().base + voff;
    wf.cu().raw_cu().notify_vgpr_write(&wf, reg, lane_mask, byte_mask);
    wf.cu().raw_cu().notify_vgpr_write(&wf, reg + 1, lane_mask, byte_mask);
  }
}

const void *Operand::full_execution_backend() {
  static const ExecutionBackend backend{
      &Operand::simd_capable_exec,
      &Operand::read_lane_chunk_exec,
      &Operand::write_lane_chunk_exec,
      &Operand::read_scalar_exec,
      &Operand::read_lane_exec,
      &Operand::write_scalar_exec,
      &Operand::write_lane_exec,
      &Operand::read_lane64_exec,
      &Operand::write_lane64_exec,
      &Operand::read_scalar64_exec,
      &Operand::write_scalar64_exec,
      &Operand::simd_vgpr_base_exec,
      &Operand::simd_vgpr_storage_exec,
      &Operand::simd_vgpr_storage_mut_exec,
      &Operand::simd_vgpr_storage64_exec,
      &Operand::simd_vgpr_storage64_mut_exec,
      &Operand::simd_notify_read_exec,
      &Operand::simd_notify_read_mut_exec,
      &Operand::simd_notify_read64_exec,
      &Operand::simd_notify_read64_mut_exec,
      &Operand::simd_notify_write_mut_exec,
      &Operand::simd_notify_write64_mut_exec,
  };
  return &backend;
}

bool Operand::full_execution_backend_complete() {
  const auto is_complete = [](const ExecutionBackend &backend) {
    return backend.simd_capable != nullptr && backend.read_lane_chunk != nullptr &&
           backend.write_lane_chunk != nullptr && backend.read_scalar != nullptr &&
           backend.read_lane != nullptr && backend.write_scalar != nullptr &&
           backend.write_lane != nullptr && backend.read_lane64 != nullptr &&
           backend.write_lane64 != nullptr && backend.read_scalar64 != nullptr &&
           backend.write_scalar64 != nullptr && backend.simd_vgpr_base != nullptr &&
           backend.simd_vgpr_storage != nullptr && backend.simd_vgpr_storage_mut != nullptr &&
           backend.simd_vgpr_storage64 != nullptr && backend.simd_vgpr_storage64_mut != nullptr &&
           backend.simd_notify_read != nullptr && backend.simd_notify_read_mut != nullptr &&
           backend.simd_notify_read64 != nullptr && backend.simd_notify_read64_mut != nullptr &&
           backend.simd_notify_write_mut != nullptr && backend.simd_notify_write64_mut != nullptr;
  };
  return is_complete(*static_cast<const ExecutionBackend *>(full_execution_backend()));
}

} // namespace gfx1250
} // namespace rocjitsu
