/*
 * Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/* This file is automatically generated. DO NOT EDIT IT. To make
 * changes, edit the .yml files under doc/mcdi/ and rebuild this file
 * with "make mcdi_headers". */

#pragma once

/* IFOE_TELEM_CAT enum: Enum defining the different categories of Telemetry.
 * Clients can request to receive a telemetry collection with all or a subset
 * of the categories included, subject to permissions.
 */
/* enum: Telemetry associated with the IFoE data path. Telemetry in this
 * category is defined as a dataset per IFoE Station.
 */
#define IFOE_TELEM_CAT_IFOE 0x0
/* enum: Telemetry associated with the ethernet switch (EX). Telemetry in this
 * category is defined as a dataset per IFoE Station.
 */
#define IFOE_TELEM_CAT_SWITCH 0x1
/* enum: Telemetry associated with the XRSEC encrypt/decrypt block. Telemetry
 * in this category is defined as a dataset per IFoE Station.
 */
#define IFOE_TELEM_CAT_CRYPTO 0x2
/* enum: Telemetry associated with the XRPFC Priority Flow Control block.
 * Telemetry in this category is defined as a dataset per Network Port.
 */
#define IFOE_TELEM_CAT_PFC 0x3
/* enum: Telemetry associated with the Network Port MACs. Telemetry in this
 * category is defined as a dataset per Network Port.
 */
#define IFOE_TELEM_CAT_NETPORT 0x4
/* enum: Telemetry derived/constructed by software associated with each IFoE
 * Station, for example the IFoE logical link status
 */
#define IFOE_TELEM_CAT_DERIVED_IFOE 0x5
/* enum: Telemetry derived/constructed by software associated with each Network
 * Port instance, for example the Network Port status
 */
#define IFOE_TELEM_CAT_DERIVED_NETPORT 0x6
/* enum: Debug telemetry associated with the IFoE data path. Telemetry in this
 * category is defined per IFoE Station.
 */
#define IFOE_TELEM_CAT_IFOE_DEBUG 0x7
/* enum: Telemetry associated with the ethernet PHYs. Telemetry in this
 * category is defined as a dataset per Serdes lane.
 */
#define IFOE_TELEM_CAT_PHY 0x8

/* IFOE_TELEM_LINK_STATUS structuredef: Flags indicating the IFoE logical link
 * status. The flags defined here apply to the telemetry data for
 * IFOE_LOGICAL_LINK_STATUS.
 */
#define IFOE_TELEM_LINK_STATUS_LEN 8
#define IFOE_TELEM_LINK_STATUS_FLAGS_OFST 0
#define IFOE_TELEM_LINK_STATUS_FLAGS_LEN 8
#define IFOE_TELEM_LINK_STATUS_FLAGS_LO_OFST 0
#define IFOE_TELEM_LINK_STATUS_FLAGS_LO_LEN 4
#define IFOE_TELEM_LINK_STATUS_FLAGS_LO_LBN 0
#define IFOE_TELEM_LINK_STATUS_FLAGS_LO_WIDTH 32
#define IFOE_TELEM_LINK_STATUS_FLAGS_HI_OFST 4
#define IFOE_TELEM_LINK_STATUS_FLAGS_HI_LEN 4
#define IFOE_TELEM_LINK_STATUS_FLAGS_HI_LBN 32
#define IFOE_TELEM_LINK_STATUS_FLAGS_HI_WIDTH 32
#define IFOE_TELEM_LINK_STATUS_LINK_DOWN_OFST 0
#define IFOE_TELEM_LINK_STATUS_LINK_DOWN_LBN 0
#define IFOE_TELEM_LINK_STATUS_LINK_DOWN_WIDTH 1
#define IFOE_TELEM_LINK_STATUS_LINK_DEGRADED_OFST 0
#define IFOE_TELEM_LINK_STATUS_LINK_DEGRADED_LBN 1
#define IFOE_TELEM_LINK_STATUS_LINK_DEGRADED_WIDTH 1
#define IFOE_TELEM_LINK_STATUS_NETPORT_FAULT_OFST 0
#define IFOE_TELEM_LINK_STATUS_NETPORT_FAULT_LBN 32
#define IFOE_TELEM_LINK_STATUS_NETPORT_FAULT_WIDTH 4
#define IFOE_TELEM_LINK_STATUS_FLAGS_LBN 0
#define IFOE_TELEM_LINK_STATUS_FLAGS_WIDTH 64

/* IFOE_TELEM_NETPORT_STATUS structuredef: Flags indicating the status of a
 * Network Port. The flags defined here apply to the telemetry data for
 * NETPORT_LINK_STATUS. A value of 0 means there that the link is up and there
 * are no faults.
 */
#define IFOE_TELEM_NETPORT_STATUS_LEN 8
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_LEN 8
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_LO_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_LO_LEN 4
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_LO_LBN 0
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_LO_WIDTH 32
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_HI_OFST 4
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_HI_LEN 4
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_HI_LBN 32
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_HI_WIDTH 32
#define IFOE_TELEM_NETPORT_STATUS_LINK_DOWN_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_LINK_DOWN_LBN 0
#define IFOE_TELEM_NETPORT_STATUS_LINK_DOWN_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_NO_PHY_LINK_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_NO_PHY_LINK_LBN 1
#define IFOE_TELEM_NETPORT_STATUS_NO_PHY_LINK_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_PMA_NO_CDR_LOCK_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_PMA_NO_CDR_LOCK_LBN 9
#define IFOE_TELEM_NETPORT_STATUS_PMA_NO_CDR_LOCK_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_PMA_LOS_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_PMA_LOS_LBN 10
#define IFOE_TELEM_NETPORT_STATUS_PMA_LOS_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_BLOCK_LOCK_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_BLOCK_LOCK_LBN 11
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_BLOCK_LOCK_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_AM_LOCK_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_AM_LOCK_LBN 12
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_AM_LOCK_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_ALIGN_LOCK_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_ALIGN_LOCK_LBN 13
#define IFOE_TELEM_NETPORT_STATUS_PCS_NO_ALIGN_LOCK_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_PCS_HI_BER_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_PCS_HI_BER_LBN 14
#define IFOE_TELEM_NETPORT_STATUS_PCS_HI_BER_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_FEC_NO_LOCK_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_FEC_NO_LOCK_LBN 15
#define IFOE_TELEM_NETPORT_STATUS_FEC_NO_LOCK_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_FEC_HI_SER_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_FEC_HI_SER_LBN 16
#define IFOE_TELEM_NETPORT_STATUS_FEC_HI_SER_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_FEC_LOCAL_DEGRADED_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_FEC_LOCAL_DEGRADED_LBN 17
#define IFOE_TELEM_NETPORT_STATUS_FEC_LOCAL_DEGRADED_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_FEC_RM_DEGRADED_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_FEC_RM_DEGRADED_LBN 18
#define IFOE_TELEM_NETPORT_STATUS_FEC_RM_DEGRADED_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_FEC_DEGRADED_SER_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_FEC_DEGRADED_SER_LBN 19
#define IFOE_TELEM_NETPORT_STATUS_FEC_DEGRADED_SER_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_AN_BP_FAILED_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_AN_BP_FAILED_LBN 21
#define IFOE_TELEM_NETPORT_STATUS_AN_BP_FAILED_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_AN_NP_FAILED_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_AN_NP_FAILED_LBN 22
#define IFOE_TELEM_NETPORT_STATUS_AN_NP_FAILED_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_AN_NO_HCD_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_AN_NO_HCD_LBN 23
#define IFOE_TELEM_NETPORT_STATUS_AN_NO_HCD_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_LOCAL_FRAME_LOCK_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_LOCAL_FRAME_LOCK_LBN 24
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_LOCAL_FRAME_LOCK_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_RM_FRAME_LOCK_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_RM_FRAME_LOCK_LBN 25
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_RM_FRAME_LOCK_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_RX_READY_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_RX_READY_LBN 26
#define IFOE_TELEM_NETPORT_STATUS_LT_NO_RX_READY_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_MAC_LOCAL_FAULT_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_MAC_LOCAL_FAULT_LBN 32
#define IFOE_TELEM_NETPORT_STATUS_MAC_LOCAL_FAULT_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_MAC_REMOTE_FAULT_OFST 0
#define IFOE_TELEM_NETPORT_STATUS_MAC_REMOTE_FAULT_LBN 33
#define IFOE_TELEM_NETPORT_STATUS_MAC_REMOTE_FAULT_WIDTH 1
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_LBN 0
#define IFOE_TELEM_NETPORT_STATUS_FLAGS_WIDTH 64

/* IFOE_TELEM_ID structuredef: Definitions for the Telemetry IDs for IFoE.
 * These IDs are immutable. Additional IDs may be added but existing IDs must
 * not be modified.
 */
#define IFOE_TELEM_ID_LEN 8
/* Reserved field - set to 0 */
#define IFOE_TELEM_ID_RSVD_OFST 4
#define IFOE_TELEM_ID_RSVD_LEN 4
#define IFOE_TELEM_ID_RSVD_LBN 32
#define IFOE_TELEM_ID_RSVD_WIDTH 32
#define IFOE_TELEM_ID_CATEGORY_OFST 3
#define IFOE_TELEM_ID_CATEGORY_LEN 1
/* enum property: index */
/*            Enum values, see field(s): */
/*               IFOE_TELEM_CAT */
#define IFOE_TELEM_ID_CATEGORY_LBN 24
#define IFOE_TELEM_ID_CATEGORY_WIDTH 8
/* ID that is unique within each telemetry category */
#define IFOE_TELEM_ID_PER_CAT_ID_OFST 0
#define IFOE_TELEM_ID_PER_CAT_ID_LEN 3
#define IFOE_TELEM_ID_PER_CAT_ID_LBN 0
#define IFOE_TELEM_ID_PER_CAT_ID_WIDTH 24
/* Fully-formed unique ID for a telemetry item */
#define IFOE_TELEM_ID_ID_OFST 0
#define IFOE_TELEM_ID_ID_LEN 8
#define IFOE_TELEM_ID_ID_LO_OFST 0
#define IFOE_TELEM_ID_ID_LO_LEN 4
#define IFOE_TELEM_ID_ID_LO_LBN 0
#define IFOE_TELEM_ID_ID_LO_WIDTH 32
#define IFOE_TELEM_ID_ID_HI_OFST 4
#define IFOE_TELEM_ID_ID_HI_LEN 4
#define IFOE_TELEM_ID_ID_HI_LBN 32
#define IFOE_TELEM_ID_ID_HI_WIDTH 32
/* enum property: index */
/* enum: *** Telemetry IDs for the IFoE datapath *** Count for write requests
 * drained from the request elastic buffer
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_WR_REQ 0x1
/* enum: Count for read requests drained from the request elastic buffer */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_REQ 0x2
/* enum: Count for atomic requests drained from the request elastic buffer */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_ATM_REQ 0x3
/* enum: Count for originator data beats drained from the corresponding elastic
 * buffer
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_ORIG_DATA 0x4
/* enum: Count for request parcel beats generated by the packer */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_PCL 0x5
/* enum: Count for write responses drained from the corresponding elastic
 * buffer
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_WR_RSP 0x6
/* enum: Count for read responses drained from the corresponding elastic buffer
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_RSP 0x7
/* enum: Count of clock cycles during which request elastic buffer is full */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_EB_FULL 0x8
/* enum: Count of clock cycles during which request elastic buffer is empty */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_EB_EMPTY 0x9
/* enum: Count of clock cycles during which originator data elastic buffer is
 * full
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_ORIG_DATA_EB_FULL 0xa
/* enum: Count of clock cycles during which originator data elastic buffer is
 * empty
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_ORIG_DATA_EB_EMPTY 0xb
/* enum: Count of clock cycles during which write response elastic buffer is
 * full
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_WR_RSP_EB_FULL 0xc
/* enum: Count of clock cycles during which write response elastic buffer is
 * empty
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_WR_RSP_EB_EMPTY 0xd
/* enum: Count of clock cycles during which read response elastic buffer is
 * full
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_RSP_EB_FULL 0xe
/* enum: Count of clock cycles during which read response elastic buffer is
 * empty
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_RSP_EB_EMPTY 0xf
/* enum: Count of clock cycles during which request parcel queue is full */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_PCL_FULL 0x10
/* enum: Count of clock cycles during which request parcel queue is empty */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_PCL_EMPTY 0x11
/* enum: Count of clock cycles during which write response parcel queue is full
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_WR_RSP_PCL_FULL 0x12
/* enum: Count of clock cycles during which write response parcel queue is
 * empty
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_WR_RSP_PCL_EMPTY 0x13
/* enum: Count of clock cycles during which read response parcel queue is full
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_RSP_PCL_FULL 0x14
/* enum: Count of clock cycles during which read response parcel queue is empty
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_RSP_PCL_EMPTY 0x15
/* enum: Count of clock cycles during which request buffer pool is full */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_POOL_FULL 0x16
/* enum: Count of clock cycles during which request buffer pool is empty */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_POOL_EMPTY 0x17
/* enum: Count of clock cycles during which response buffer pool is full */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RSP_POOL_FULL 0x18
/* enum: Count of clock cycles during which response buffer pool is empty */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RSP_POOL_EMPTY 0x19
/* enum: Count of errored originator data beats received through the SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_ORIG_DATA_ERROR 0x1a
/* enum: Count of errored read response data beats received through the SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_RSP_DATA_ERROR 0x1b
/* enum: Count of credits consumed by the originator in the request SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_CREDIT_CONSUMED 0x1c
/* enum: Count of credits released to the originator in the request SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_REQ_CREDIT_RELEASED 0x1d
/* enum: Count of credits consumed by the originator in the originator data SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_ORIG_DATA_CREDIT_CONSUMED 0x1e
/* enum: Count of credits released to the originator in the originator data SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_ORIG_DATA_CREDIT_RELEASED 0x1f
/* enum: Count of credits consumed by the completer in the write response SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_WR_RSP_CREDIT_CONSUMED 0x20
/* enum: Count of credits released to the completer in the write response SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_WR_RSP_CREDIT_RELEASED 0x21
/* enum: Count of credits consumed by the completer in the read response SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_RSP_CREDIT_CONSUMED 0x22
/* enum: Count of credits released to the completer in the read response SDP
 * interface
 */
#define IFOE_TELEM_ID_IFOE_SDP_TX_PACK_RD_RSP_CREDIT_RELEASED 0x23
/* enum: Request free block return delayed */
#define IFOE_TELEM_ID_IFOE_WENG_BSTATE_FREE_BLK_DELAY_REQ 0x1001
/* enum: Response free block return delayed */
#define IFOE_TELEM_ID_IFOE_WENG_BSTATE_FREE_BLK_DELAY_RES 0x1002
/* enum: Request stream SDP messages */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_REQ 0x1003
/* enum: Response stream SDP messages */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_RES 0x1004
/* enum: Request stream SDP messages with force set */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_FORCE_REQ 0x1005
/* enum: Response stream SDP messages with force set */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_FORCE_RES 0x1006
/* enum: Request stream SDP messages with chain set */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_CHAIN_REQ 0x1007
/* enum: Response stream SDP messages with chain set */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_CHAIN_RES 0x1008
/* enum: Request stream SDP message words */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_WORD_REQ 0x1009
/* enum: Response stream SDP message words */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_WORD_RES 0x100a
/* enum: Request stream SDP message data in 8 byte granules */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_LENGTH_REQ 0x100b
/* enum: Response stream SDP message data in 8 byte granules */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_LENGTH_RES 0x100c
/* enum: Request stream packets opened */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_PKT_OPEN_REQ 0x100d
/* enum: Response stream packets opened */
#define IFOE_TELEM_ID_IFOE_WENG_OP_SDP_PKT_OPEN_RES 0x100e
/* enum: Request packets payload terminated in 8 byte granules */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_PAYLOAD_REQ 0x100f
/* enum: Response packets payload terminated in 8 byte granules */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_PAYLOAD_RES 0x1010
/* enum: Request packets generated due to MTU threshold */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_MTU_REQ 0x1011
/* enum: Response packets generated due to MTU threshold */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_MTU_RES 0x1012
/* enum: Request packets generated due to forced SDP messages */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_FORCE_REQ 0x1013
/* enum: Response packets generated due to forced SDP messages */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_FORCE_RES 0x1014
/* enum: Request packets generated due to timer expiry */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_EXPIRY_REQ 0x1015
/* enum: Response packets generated due to timer expiry */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_EXPIRY_RES 0x1016
/* enum: Request packets without forced messages delayed by chain */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_CHAIN_DELAY_REQ 0x1017
/* enum: Response packets without forced messages delayed by chain */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_CHAIN_DELAY_RES 0x1018
/* enum: Request packets with forced messages delayed by chain */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_FORCE_CHAIN_DELAY_REQ 0x1019
/* enum: Response packets with forced messages delayed by chain */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_FORCE_CHAIN_DELAY_RES 0x101a
/* enum: Request packets that reach MTU threshold due to the scheduler
 * acknowledgement
 */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_MTU_HOLD_DELAY_REQ 0x101b
/* enum: Response packets that reach MTU threshold due to the scheduler
 * acknowledgement
 */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_MTU_HOLD_DELAY_RES 0x101c
/* enum: Request packets with force flag set delayed due to the scheduler
 * acknowledgement
 */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_FORCE_HOLD_DELAY_REQ 0x101d
/* enum: Response packets with force flag set delayed due to the scheduler
 * acknowledgement
 */
#define IFOE_TELEM_ID_IFOE_WENG_EVICTION_FORCE_HOLD_DELAY_RES 0x101e
/* enum: Number of Read Engine scheduled read requests */
#define IFOE_TELEM_ID_IFOE_RENG_READ_SCH_IN 0x101f
/* enum: Number of Read Engine output packets sent to Encapsulation */
#define IFOE_TELEM_ID_IFOE_RENG_READ_PKT_OUT 0x1020
/* enum: Number of Read Engine scheduled free requests */
#define IFOE_TELEM_ID_IFOE_RENG_FREE_SCH_IN 0x1021
/* enum: Number of Read Engine freed head blocks, or freed packets */
#define IFOE_TELEM_ID_IFOE_RENG_FREE_PKT_OUT 0x1022
/* enum: Number of Read Engine freed blocks */
#define IFOE_TELEM_ID_IFOE_RENG_FREE_BLK_OUT 0x1023
/* enum: Count of the number of xrsec egress packets for network port 0 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PKT_EGRESS_XRSEC_NPORT_0 0x2001
/* enum: Count of the number of xrsec egress packets for network port 1 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PKT_EGRESS_XRSEC_NPORT_1 0x2002
/* enum: Count of the number of xrsec egress packets for network port 2 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PKT_EGRESS_XRSEC_NPORT_2 0x2003
/* enum: Count of the number of xrsec egress packets for network port 3 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PKT_EGRESS_XRSEC_NPORT_3 0x2004
/* enum: Count of the payload in 8B granules sent on xrsec egress network port
 * 0
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PAYL_LEN_EGRESS_XRSEC_NPORT_0 0x2005
/* enum: Count of the payload in 8B granules sent on xrsec egress network port
 * 1
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PAYL_LEN_EGRESS_XRSEC_NPORT_1 0x2006
/* enum: Count of the payload in 8B granules sent on xrsec egress network port
 * 2
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PAYL_LEN_EGRESS_XRSEC_NPORT_2 0x2007
/* enum: Count of the payload in 8B granules sent on xrsec egress network port
 * 3
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PAYL_LEN_EGRESS_XRSEC_NPORT_3 0x2008
/* enum: Count of the header (inc. metadata) in bytes sent on xrsec egress
 * network port 0
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_HDR_LEN_EGRESS_XRSEC_NPORT_0 0x2009
/* enum: Count of the header (inc. metadata) in bytes sent on xrsec egress
 * network port 1
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_HDR_LEN_EGRESS_XRSEC_NPORT_1 0x200a
/* enum: Count of the header (inc. metadata) in bytes sent on xrsec egress
 * network port 2
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_HDR_LEN_EGRESS_XRSEC_NPORT_2 0x200b
/* enum: Count of the header (inc. metadata) in bytes sent on xrsec egress
 * network port 3
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_HDR_LEN_EGRESS_XRSEC_NPORT_3 0x200c
/* enum: Count of the number of xrsec egress valid cycles (valid=1 && ready=1)
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_VALID_EGRESS_XRSEC 0x200d
/* enum: Count of the number of xrsec egress stalled cycles (valid=1 &&
 * ready=0)
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_STALL_EGRESS_XRSEC 0x200e
/* enum: Count of the ingress packets from TX2 Read Engine */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_PKT_INGRESS 0x200f
/* enum: Count of the ingress valid cycles from TX2 Read Engine (valid=1 &&
 * ready=0)
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_VALID_INGRESS 0x2010
/* enum: Count of the ingress stalled cycles from TX2 Read Engine (valid=1 &&
 * ready=0)
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_STALL_INGRESS 0x2011
/* enum: Count of the context ingress valid cycles from TX Scheduler for
 * network port 0
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_VALID_CNTXT_INGRESS_NPORT_0 0x2012
/* enum: Count of the context ingress valid cycles from TX Scheduler for
 * network port 1
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_VALID_CNTXT_INGRESS_NPORT_1 0x2013
/* enum: Count of the context ingress valid cycles from TX Scheduler for
 * network port 2
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_VALID_CNTXT_INGRESS_NPORT_2 0x2014
/* enum: Count of the context ingress valid cycles from TX Scheduler for
 * network port 3
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_VALID_CNTXT_INGRESS_NPORT_3 0x2015
/* enum: Count of the context ingress stalled cycles from TX Scheduler (valid=1
 * && ready=0)
 */
#define IFOE_TELEM_ID_IFOE_TX_ENCAP_STALL_CNTXT_INGRESS 0x2016
/* enum: Number of streams in INACTIVE state */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_INACTIVE_STREAMS 0x3001
/* enum: Number of streams in ACTIVE state */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_ACTIVE_STREAMS 0x3002
/* enum: Number of streams in PAUSED state */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_PAUSED_STREAMS 0x3003
/* enum: Number of streams with boosted priority */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_BOOSTED_PRI_STREAMS 0x3004
/* enum: Number of streams with empty send + replay queues */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_EMPTY_QUEUE_STREAMS 0x3005
/* enum: Number of streams with empty send queues */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_EMPTY_SEND_QUEUE_STREAMS 0x3006
/* enum: Number of request packets in the scheduler */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_REQ_PKTS 0x3007
/* enum: Number of response packets in the scheduler */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_RES_PKTS 0x3008
/* enum: Number of low priority packets in the network port 0 Request queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_LOW_PRI_REQ_PKTS_NPORT_0 0x3009
/* enum: Number of high priority packets in the network port 0 Request queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_HIGH_PRI_REQ_PKTS_NPORT_0 0x300a
/* enum: Number of low priority packets in the network port 0 Response queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_LOW_PRI_RES_PKTS_NPORT_0 0x300b
/* enum: Number of high priority packets in the network port 0 Response queue
 */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_HIGH_PRI_RES_PKTS_NPORT_0 0x300c
/* enum: Number of low priority packets in the network port 1 Request queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_LOW_PRI_REQ_PKTS_NPORT_1 0x300d
/* enum: Number of high priority packets in the network port 1 Request queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_HIGH_PRI_REQ_PKTS_NPORT_1 0x300e
/* enum: Number of low priority packets in the network port 1 Response queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_LOW_PRI_RES_PKTS_NPORT_1 0x300f
/* enum: Number of high priority packets in the network port 1 Response queue
 */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_HIGH_PRI_RES_PKTS_NPORT_1 0x3010
/* enum: Number of low priority packets in the network port 2 Request queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_LOW_PRI_REQ_PKTS_NPORT_2 0x3011
/* enum: Number of high priority packets in the network port 2 Request queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_HIGH_PRI_REQ_PKTS_NPORT_2 0x3012
/* enum: Number of low priority packets in the network port 2 Response queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_LOW_PRI_RES_PKTS_NPORT_2 0x3013
/* enum: Number of high priority packets in the network port 2 Response queue
 */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_HIGH_PRI_RES_PKTS_NPORT_2 0x3014
/* enum: Number of low priority packets in the network port 3 Request queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_LOW_PRI_REQ_PKTS_NPORT_3 0x3015
/* enum: Number of high priority packets in the network port 3 Request queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_HIGH_PRI_REQ_PKTS_NPORT_3 0x3016
/* enum: Number of low priority packets in the network port 3 Response queue */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_LOW_PRI_RES_PKTS_NPORT_3 0x3017
/* enum: Number of high priority packets in the network port 3 Response queue
 */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_HIGH_PRI_RES_PKTS_NPORT_3 0x3018
/* enum: Number of active TXACK response streams */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_ACTIVE_TX_ACK_RES_STREAMS 0x3019
/* enum: Number of active RXACK packets */
#define IFOE_TELEM_ID_IFOE_TX_SCHED_ACTIVE_RX_ACK_PKTS 0x301a
/* enum: Count of the number of XRSEC ingress packets for network port 0 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_XRSEC_INGRESS_NPORT_0 0x4001
/* enum: Count of the number of XRSEC ingress packets for network port 1 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_XRSEC_INGRESS_NPORT_1 0x4002
/* enum: Count of the number of XRSEC ingress packets for network port 2 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_XRSEC_INGRESS_NPORT_2 0x4003
/* enum: Count of the number of XRSEC ingress packets for network port 3 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_XRSEC_INGRESS_NPORT_3 0x4004
/* enum: Count of the packet length in bytes of XRSEC ingress packets from
 * network port 0
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_LEN_XRSEC_INGRESS_NPORT_0 0x4005
/* enum: Count of the packet length in bytes of XRSEC ingress packets from
 * network port 1
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_LEN_XRSEC_INGRESS_NPORT_1 0x4006
/* enum: Count of the packet length in bytes of XRSEC ingress packets from
 * network port 2
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_LEN_XRSEC_INGRESS_NPORT_2 0x4007
/* enum: Count of the packet length in bytes of XRSEC ingress packets from
 * network port 3
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_LEN_XRSEC_INGRESS_NPORT_3 0x4008
/* enum: Count of the payload in 8B granules of XRSEC ingress packets from
 * network port 0
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PAYL_LEN_XRSEC_INGRESS_NPORT_0 0x4009
/* enum: Count of the payload in 8B granules of XRSEC ingress packets from
 * network port 1
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PAYL_LEN_XRSEC_INGRESS_NPORT_1 0x400a
/* enum: Count of the payload in 8B granules of XRSEC ingress packets from
 * network port 2
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PAYL_LEN_XRSEC_INGRESS_NPORT_2 0x400b
/* enum: Count of the payload in 8B granules of XRSEC ingress packets from
 * network port 3
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PAYL_LEN_XRSEC_INGRESS_NPORT_3 0x400c
/* enum: Count of the number of xrsec ingress valid cycles (valid=1 && ready=1)
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_VALID_INGRESS_XRSEC 0x400d
/* enum: Count of the number of xrsec ingress stalled cycles (valid=1 &&
 * ready=0)
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_STALL_INGRESS_XRSEC 0x400e
/* enum: Count of the number of egress packets for requests sent to RX Unpack
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_EGRESS_REQ 0x400f
/* enum: Count of the number of egress packets for responses sent to RX Unpack
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_PKT_EGRESS_RSP 0x4010
/* enum: Count of the number of packet egress valid cycles sent to RX Unpack */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_VALID_EGRESS 0x4011
/* enum: Count of the number of egress credit info for requests sent to RX
 * Unpack
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_CRDT_EGRESS_REQ 0x4012
/* enum: Count of the number of egress credit info for responses sent to RX
 * Unpack
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_CRDT_EGRESS_RSP 0x4013
/* enum: Count of the number of egress TX ACKs for requests sent to TX
 * Scheduler
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_TX_ACK_EGRESS_REQ 0x4014
/* enum: Count of the number of egress TX ACKs for responses sent to TX
 * Scheduler
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_TX_ACK_EGRESS_RSP 0x4015
/* enum: Count of the number of egress TX NAKs for requests sent to TX
 * Scheduler
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_TX_NAK_EGRESS_REQ 0x4016
/* enum: Count of the number of egress TX NAKs for responses sent to TX
 * Scheduler
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_TX_NAK_EGRESS_RSP 0x4017
/* enum: Count of the number of egress RX ACKs for requests sent to TX
 * Scheduler
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_RX_ACK_EGRESS_REQ 0x4018
/* enum: Count of the number of egress RX ACKs for responses sent to TX
 * Scheduler
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_RX_ACK_EGRESS_RSP 0x4019
/* enum: Count of the number of egress RX NAKs for requests sent to TX
 * Scheduler
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_RX_NAK_EGRESS_REQ 0x401a
/* enum: Count of the number of egress RX NAKs for responses sent to TX
 * Scheduler
 */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_RX_NAK_EGRESS_RSP 0x401b
/* enum: Count of dropped packets */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_DROPPED_PKTS 0x401c
/* enum: Init busy signal for sequence number RAM */
#define IFOE_TELEM_ID_IFOE_RX_DECAP_INIT_BUSY 0x401d
/* enum: Live count of total network Request credits consumed. This is an
 * accumulation of the payload credits plus overhead based on packets received
 * by RX1.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_REQ_TOTAL_CREDITS_CONSUMED 0x5001
/* enum: Live count of total network Request credits returned on credit
 * interface. This is an accumulation of the payload credits returned due to
 * parcels being read from the parcel buffer.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_REQ_PAYLOAD_CREDITS_RETURNED 0x5002
/* enum: Live count of total network Request excess credits returned on credit
 * interface. This is an accumulation of any credits returned due to packets
 * being dropped or packet overheads.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_REQ_EXCESS_CREDITS_RETURNED 0x5003
/* enum: Live count of total network Response credits consumed. This is an
 * accumulation of the payload credits plus overhead based on packets received
 * by RX1.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RSP_TOTAL_CREDITS_CONSUMED 0x5004
/* enum: Live count of total network Response credits returned on credit
 * interface. This is an accumulation of the payload credits returned due to
 * parcels being read from the parcel buffer.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RSP_PAYLOAD_CREDITS_RETURNED 0x5005
/* enum: Live count of total network Response excess credits returned on credit
 * interface. This is an accumulation of any credits returned due to packets
 * being dropped or packet overheads.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RSP_EXCESS_CREDITS_RETURNED 0x5006
/* enum: Live count of number of OrigReq beats written into the OrigReq SDP
 * output buffer
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_REQ_CREDITS_CONSUMED 0x5007
/* enum: Live count of credits returned for the OrigReq SDP interface */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_REQ_CREDITS_RETURNED 0x5008
/* enum: Live count of number of Origdata beats written into the OrigData SDP
 * output buffer
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_ORIGDATA_CREDITS_CONSUMED 0x5009
/* enum: Live count of credits returned for the OrigData SDP interface */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_ORIGDATA_CREDITS_RETURNED 0x500a
/* enum: Live count of number of WrRsp beats written into the WrRsp SDP output
 * buffer
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_WRRSP_CREDITS_CONSUMED 0x500b
/* enum: Live count of credits returned for the WrRsp SDP interface */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_WRRSP_CREDITS_RETURNED 0x500c
/* enum: Live count of number of RdRsp beats written into the RdRsp SDP output
 * buffer
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RDRSP_CREDITS_CONSUMED 0x500d
/* enum: Live count of credits returned for the RdRsp SDP interface */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RDRSP_CREDITS_RETURNED 0x500e
/* enum: Count of number of cycles for which the input request buffer read is
 * stalled. This can be due to credit starvation on SDP or time to process
 * parcels.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_REQ_CYCLES_STALLED 0x500f
/* enum: Count of number of cycles for which the input response buffer read is
 * stalled. This can be due to credit starvation on SDP or time to process
 * parcels.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RSP_CYCLES_STALLED 0x5010
/* enum: Count of number of cycles for which Requests parcels are held due to
 * credit starvation on OrigReq or OrigData SDP interface or running out of
 * retags.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_REQ_CYCLES_STALLED_CNT 0x5011
/* enum: Count of number of cycles for which Response parcels are held due to
 * credit starvation on RdRsp or WrRsp SDP interface or running out of retags.
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RSP_CYCLES_STALLED_CNT 0x5012
/* enum: Count of number of retags used- expect one per each Request parcel
 * processed
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RETAG_USED 0x5013
/* enum: Count of number of retags freed due to all expected responses for a
 * request being received
 */
#define IFOE_TELEM_ID_IFOE_SDP_RX_UNPACK_RETAG_FREED 0x5014
/* enum: *** Telemetry IDs for the EX switch *** Count of non-IFoE packets read
 * by firmware
 */
#define IFOE_TELEM_ID_SWITCH_RX_NONIFOE_PKTS 0x1000001
/* enum: Count of bytes of non-IFoE traffic read by firmware */
#define IFOE_TELEM_ID_SWITCH_RX_NONIFOE_BYTES 0x1000002
/* enum: Count of packets received from the network and dropped due to
 * insufficient free space in the switch
 */
#define IFOE_TELEM_ID_SWITCH_RX_DROPPED_PKTS 0x1000003
/* enum: Count of bytes received from the network and dropped due to
 * insufficient free space in the switch
 */
#define IFOE_TELEM_ID_SWITCH_RX_DROPPED_BYTES 0x1000004
/* enum: Count of non-IFoE packets written by firmware */
#define IFOE_TELEM_ID_SWITCH_TX_NONIFOE_PKTS 0x1000005
/* enum: Count of bytes of non-IFoE traffic written by firmware */
#define IFOE_TELEM_ID_SWITCH_TX_NONIFOE_BYTES 0x1000006
/* enum: *** Telemetry IDs for the encrypt/decrypt hardware *** Flag indicating
 * that initialization of the TX crypto core is complete
 */
#define IFOE_TELEM_ID_CRYPTO_TX_CORE_INIT_DONE 0x2000001
/* enum: Flag indicating that initialization of the RX crypto core is complete
 */
#define IFOE_TELEM_ID_CRYPTO_RX_CORE_INIT_DONE 0x2000002
/* enum: Count of all bytes into ingress of TX encryption core */
#define IFOE_TELEM_ID_CRYPTO_TX_INGRESS_TOTAL_BYTES 0x2000003
/* enum: Count of all packets into ingress of TX encryption core */
#define IFOE_TELEM_ID_CRYPTO_TX_INGRESS_TOTAL_PKTS 0x2000004
/* enum: Count of all bytes out of egress of TX encryption core */
#define IFOE_TELEM_ID_CRYPTO_TX_EGRESS_TOTAL_BYTES 0x2000005
/* enum: Count of all packets out of egress of TX encryption core */
#define IFOE_TELEM_ID_CRYPTO_TX_EGRESS_TOTAL_PKTS 0x2000006
/* enum: Count of all bytes into ingress of RX decryption core */
#define IFOE_TELEM_ID_CRYPTO_RX_INGRESS_TOTAL_BYTES 0x2000007
/* enum: Count of all packets into ingress of RX decryption core */
#define IFOE_TELEM_ID_CRYPTO_RX_INGRESS_TOTAL_PKTS 0x2000008
/* enum: Count of all bytes out of egress of RX encryption core */
#define IFOE_TELEM_ID_CRYPTO_RX_EGRESS_TOTAL_BYTES 0x2000009
/* enum: Count of all packets out of egress of RX encryption core */
#define IFOE_TELEM_ID_CRYPTO_RX_EGRESS_TOTAL_PKTS 0x200000a
/* enum: Total payload bytes of all IFoE packets encrypted */
#define IFOE_TELEM_ID_CRYPTO_TX_TOTAL_ENCRYPTED_BYTES 0x2001001
/* enum: Total number of good IFoE packets encrypted */
#define IFOE_TELEM_ID_CRYPTO_TX_TOTAL_ENCRYPTED_PKTS 0x2001002
/* enum: Total number of IFoE packets processed containing an EOP error */
#define IFOE_TELEM_ID_CRYPTO_TX_TOTAL_ERROR_PKTS 0x2001003
/* enum: Total payload bytes of all IFoE packets decrypted */
#define IFOE_TELEM_ID_CRYPTO_RX_TOTAL_DECRYPTED_BYTES 0x2001004
/* enum: Total number of good IFoE packets decrypted */
#define IFOE_TELEM_ID_CRYPTO_RX_TOTAL_DECRYPTED_PKTS 0x2001005
/* enum: Total number of IFoE packets processed that failed validation due to
 * either an ICV check failure, a framing error or an EOP error
 */
#define IFOE_TELEM_ID_CRYPTO_RX_TOTAL_BAD_PKTS 0x2001006
/* enum: Total number of IFoE packets processed containing a framing or EOP
 * error.
 */
#define IFOE_TELEM_ID_CRYPTO_RX_TOTAL_ERROR_PKTS 0x2001007
/* enum: *** Telemetry IDs for the priority flow control block *** Total number
 * of Global Pause packets transmitted
 */
#define IFOE_TELEM_ID_PFC_TX_PAUSE_PACKETS_SENT 0x3000001
/* enum: Total number of packets transmitted with PFC priority 0 */
#define IFOE_TELEM_ID_PFC_TX_PFC_PRIO0_PACKETS_SENT 0x3000002
/* enum: Total number of packets transmitted with PFC priority 1 */
#define IFOE_TELEM_ID_PFC_TX_PFC_PRIO1_PACKETS_SENT 0x3000003
/* enum: Total number of packets transmitted with PFC priority 2 */
#define IFOE_TELEM_ID_PFC_TX_PFC_PRIO2_PACKETS_SENT 0x3000004
/* enum: Total number of packets transmitted with PFC priority 3 */
#define IFOE_TELEM_ID_PFC_TX_PFC_PRIO3_PACKETS_SENT 0x3000005
/* enum: Total number of packets transmitted with PFC priority 4 */
#define IFOE_TELEM_ID_PFC_TX_PFC_PRIO4_PACKETS_SENT 0x3000006
/* enum: Total number of packets transmitted with PFC priority 5 */
#define IFOE_TELEM_ID_PFC_TX_PFC_PRIO5_PACKETS_SENT 0x3000007
/* enum: Total number of packets transmitted with PFC priority 6 */
#define IFOE_TELEM_ID_PFC_TX_PFC_PRIO6_PACKETS_SENT 0x3000008
/* enum: Total number of packets transmitted with PFC priority 7 */
#define IFOE_TELEM_ID_PFC_TX_PFC_PRIO7_PACKETS_SENT 0x3000009
/* enum: Total number of Global Pause packets received */
#define IFOE_TELEM_ID_PFC_RX_PAUSE_PACKETS_RCVD 0x3001001
/* enum: Total number of packets received with PFC priority 0 */
#define IFOE_TELEM_ID_PFC_RX_PFC_PRIO0_PACKETS_RCVD 0x3001002
/* enum: Total number of packets received with PFC priority 1 */
#define IFOE_TELEM_ID_PFC_RX_PFC_PRIO1_PACKETS_RCVD 0x3001003
/* enum: Total number of packets received with PFC priority 2 */
#define IFOE_TELEM_ID_PFC_RX_PFC_PRIO2_PACKETS_RCVD 0x3001004
/* enum: Total number of packets received with PFC priority 3 */
#define IFOE_TELEM_ID_PFC_RX_PFC_PRIO3_PACKETS_RCVD 0x3001005
/* enum: Total number of packets received with PFC priority 4 */
#define IFOE_TELEM_ID_PFC_RX_PFC_PRIO4_PACKETS_RCVD 0x3001006
/* enum: Total number of packets received with PFC priority 5 */
#define IFOE_TELEM_ID_PFC_RX_PFC_PRIO5_PACKETS_RCVD 0x3001007
/* enum: Total number of packets received with PFC priority 6 */
#define IFOE_TELEM_ID_PFC_RX_PFC_PRIO6_PACKETS_RCVD 0x3001008
/* enum: Total number of packets received with PFC priority 7 */
#define IFOE_TELEM_ID_PFC_RX_PFC_PRIO7_PACKETS_RCVD 0x3001009
/* enum: Total number of bytes sent for IFoE Request TX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_TX_TOTAL_BYTES 0x3002001
/* enum: Total number of packets sent for IFoE Request TX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_TX_TOTAL_PACKETS 0x3002002
/* enum: Count of time XOFF was applied for IFoE Request TX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_TX_XOFF_TOTAL 0x3002003
/* enum: Amount of time a packet transmission was delayed due to XOFF for IFoE
 * Request TX queue
 */
#define IFOE_TELEM_ID_PFC_REQ_Q_TX_DELAY_TOTAL 0x3002004
/* enum: Number of memory pages occupied by the IFoE Request TX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_TX_FLV 0x3002005
/* enum: Time duration between XON -> XOFF and a subsequent XOFF -> XON for
 * IFoE Request TX queue
 */
#define IFOE_TELEM_ID_PFC_REQ_Q_TX_XOFF_PERIOD 0x3002006
/* enum: Flag indicating that a packet stopped in the middle when reading from
 * packet buffer for IFoE Request TX queue
 */
#define IFOE_TELEM_ID_PFC_REQ_Q_TX_UNF 0x3002007
/* enum: Boolean value indicating that the IFoE Request TX queue is empty */
#define IFOE_TELEM_ID_PFC_REQ_Q_TX_QUEUE_EMPTY 0x3002008
/* enum: Total number of bytes sent for IFoE Response TX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_TX_TOTAL_BYTES 0x3002101
/* enum: Total number of packets sent for IFoE Response TX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_TX_TOTAL_PACKETS 0x3002102
/* enum: Count of time XOFF was applied for IFoE Response TX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_TX_XOFF_TOTAL 0x3002103
/* enum: Amount of time a packet transmission was delayed due to XOFF for IFoE
 * Response TX queue
 */
#define IFOE_TELEM_ID_PFC_RES_Q_TX_DELAY_TOTAL 0x3002104
/* enum: Number of memory pages occupied by the IFoE Response TX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_TX_FLV 0x3002105
/* enum: Time duration between XON -> XOFF and a subsequent XOFF -> XON for
 * IFoE Response TX queue
 */
#define IFOE_TELEM_ID_PFC_RES_Q_TX_XOFF_PERIOD 0x3002106
/* enum: Flag indicating that a packet stopped in the middle when reading from
 * packet buffer for IFoE Response TX queue
 */
#define IFOE_TELEM_ID_PFC_RES_Q_TX_UNF 0x3002107
/* enum: Boolean value indicating that the IFoE Response TX queue is empty */
#define IFOE_TELEM_ID_PFC_RES_Q_TX_QUEUE_EMPTY 0x3002108
/* enum: Total number of bytes sent for non-IFoE traffic TX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_TX_TOTAL_BYTES 0x3002201
/* enum: Total number of packets sent for non-IFoE traffic TX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_TX_TOTAL_PACKETS 0x3002202
/* enum: Count of time XOFF was applied for non-IFoE traffic TX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_TX_XOFF_TOTAL 0x3002203
/* enum: Amount of time a packet transmission was delayed due to XOFF for non-
 * IFoE traffic TX queue
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_TX_DELAY_TOTAL 0x3002204
/* enum: Number of memory pages occupied by the non-IFoE traffic TX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_TX_FLV 0x3002205
/* enum: Time duration between XON -> XOFF and a subsequent XOFF -> XON for
 * non-IFoE traffic TX queue
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_TX_XOFF_PERIOD 0x3002206
/* enum: Flag indicating that a packet stopped in the middle when reading from
 * packet buffer for the non-IFoE traffic TX queue
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_TX_UNF 0x3002207
/* enum: Boolean value indicating that the non-IFoE traffic TX queue is empty
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_TX_QUEUE_EMPTY 0x3002208
/* enum: Total number of bytes received for IFoE Request RX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_TOTAL_BYTES 0x3003001
/* enum: Number of bytes dropped for IFoE Request RX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_DROPPED_BYTES 0x3003002
/* enum: Total number of packets received for IFoE Request RX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_TOTAL_PACKETS 0x3003003
/* enum: Number of packets dropped for IFoE Request RX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_DROPPED_PACKETS 0x3003004
/* enum: Total number of truncated packets received for IFoE Request RX queue
 */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_TRUNCATED_PACKETS 0x3003005
/* enum: Count of time XOFF was applied for IFoE Request RX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_XOFF_TOTAL 0x3003006
/* enum: Number of memory pages occupied by the IFoE Request RX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_FLV 0x3003007
/* enum: Flag indicating that a packet stopped in the middle when reading from
 * packet buffer for IFoE Request RX queue
 */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_UTF 0x3003008
/* enum: Time duration between XON -> XOFF and a subsequent XOFF -> XON for
 * IFoE Request RX queue
 */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_XOFF_PERIOD 0x3003009
/* enum: Instantaneous number of credits available for IFoE Request RX queue */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_CREDIT_INT 0x300300a
/* enum: Flags indicating that a credit error has occurred for IFoE Request RX
 * queue
 */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_CREDIT_ERR 0x300300b
/* enum: Boolean value indicating that the IFoE Request TX queue is empty */
#define IFOE_TELEM_ID_PFC_REQ_Q_RX_QUEUE_EMPTY 0x300300c
/* enum: Total number of bytes received for IFoE Response RX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_TOTAL_BYTES 0x3003101
/* enum: Number of bytes dropped for IFoE Response RX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_DROPPED_BYTES 0x3003102
/* enum: Total number of packets received for IFoE Response RX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_TOTAL_PACKETS 0x3003103
/* enum: Number of packets dropped for IFoE Response RX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_DROPPED_PACKETS 0x3003104
/* enum: Total number of truncated packets received for IFoE Response RX queue
 */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_TRUNCATED_PACKETS 0x3003105
/* enum: Count of time XOFF was applied for IFoE Response RX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_XOFF_TOTAL 0x3003106
/* enum: Number of memory pages occupied by the IFoE Response RX queue */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_FLV 0x3003107
/* enum: Flag indicating that a packet stopped in the middle when reading from
 * packet buffer for IFoE Response RX queue
 */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_UTF 0x3003108
/* enum: Time duration between XON -> XOFF and a subsequent XOFF -> XON for
 * IFoE Response RX queue
 */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_XOFF_PERIOD 0x3003109
/* enum: Instantaneous number of credits available for IFoE Response RX queue
 */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_CREDIT_INT 0x300310a
/* enum: Flags indicating that a credit error has occurred for IFoE Response RX
 * queue
 */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_CREDIT_ERR 0x300310b
/* enum: Boolean value indicating that the IFoE Response TX queue is empty */
#define IFOE_TELEM_ID_PFC_RES_Q_RX_QUEUE_EMPTY 0x300310c
/* enum: Total number of bytes received for the non-IFoE traffic RX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_TOTAL_BYTES 0x3003201
/* enum: Number of bytes dropped for the non-IFoE traffic RX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_DROPPED_BYTES 0x3003202
/* enum: Total number of packets received for the non-IFoE traffic RX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_TOTAL_PACKETS 0x3003203
/* enum: Number of packets dropped for the non-IFoE traffic RX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_DROPPED_PACKETS 0x3003204
/* enum: Total number of truncated packets received for the non-IFoE traffic RX
 * queue
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_TRUNCATED_PACKETS 0x3003205
/* enum: Count of time XOFF was applied for the non-IFoE traffic RX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_XOFF_TOTAL 0x3003206
/* enum: Number of memory pages occupied by the non-IFoE traffic RX queue */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_FLV 0x3003207
/* enum: Flag indicating that a packet stopped in the middle when reading from
 * packet buffer for the non-IFoE traffic RX queue
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_UTF 0x3003208
/* enum: Time duration between XON -> XOFF and a subsequent XOFF -> XON for the
 * non-IFoE traffic RX queue
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_XOFF_PERIOD 0x3003209
/* enum: Instantaneous number of credits available for the non-IFoE traffic RX
 * queue
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_CREDIT_INT 0x300320a
/* enum: Flags indicating that a credit error has occurred for the non-IFoE
 * traffic RX queue
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_CREDIT_ERR 0x300320b
/* enum: Boolean value indicating that the non-IFoE traffic TX queue is empty
 */
#define IFOE_TELEM_ID_PFC_NONIFOE_Q_RX_QUEUE_EMPTY 0x300320c
/* enum: Total number of bytes received for the discard RX queue */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_TOTAL_BYTES 0x3003301
/* enum: Number of bytes dropped for the discard RX queue */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_DROPPED_BYTES 0x3003302
/* enum: Total number of packets received for the discard RX queue */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_TOTAL_PACKETS 0x3003303
/* enum: Number of packets dropped for the discard RX queue */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_DROPPED_PACKETS 0x3003304
/* enum: Total number of truncated packets received for the discard RX queue */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_TRUNCATED_PACKETS 0x3003305
/* enum: Count of time XOFF was applied for the discard RX queue */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_XOFF_TOTAL 0x3003306
/* enum: Number of memory pages occupied by the discard RX queue */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_FLV 0x3003307
/* enum: Flag indicating that a packet stopped in the middle when reading from
 * packet buffer for the discard RX queue
 */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_UTF 0x3003308
/* enum: Time duration between XON -> XOFF and a subsequent XOFF -> XON for the
 * discard RX queue
 */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_XOFF_PERIOD 0x3003309
/* enum: Instantaneous number of credits available for the discard RX queue */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_CREDIT_INT 0x300330a
/* enum: Flags indicating that a credit error has occurred for the discard RX
 * queue
 */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_CREDIT_ERR 0x300330b
/* enum: Boolean value indicating that the discard TX queue is empty */
#define IFOE_TELEM_ID_PFC_DISCARD_Q_RX_QUEUE_EMPTY 0x300330c
/* enum: *** Telemetry IDs for the ethernet network ports *** Total number of
 * bytes transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_TOTAL_BYTES 0x4000001
/* enum: Total number of good bytes transmitted. This value is only incremented
 * when a packet is transmitted completely and contains no errors.
 */
#define IFOE_TELEM_ID_NETPORT_TX_TOTAL_GOOD_BYTES 0x4000002
/* enum: Total number of bad bytes transmitted. This value is only incremented
 * when a packet is not transmitted completely or contains errors.
 */
#define IFOE_TELEM_ID_NETPORT_TX_TOTAL_ERR_BYTES 0x4000003
/* enum: Total number of packets transmitted. */
#define IFOE_TELEM_ID_NETPORT_TX_TOTAL_PACKETS 0x4000004
/* enum: Total number of good bytes transmitted. This value is only incremented
 * when a packet is transmitted completely and contains no errors.
 */
#define IFOE_TELEM_ID_NETPORT_TX_TOTAL_GOOD_PACKETS 0x4000005
/* enum: Number of packets with tx_errin set to 1 to indicate an End of Packet
 * (EOP) abort.
 */
#define IFOE_TELEM_ID_NETPORT_TX_FRAME_ERROR 0x4000006
/* enum: Total number of packets greater than 64 bytes that have FCS errors */
#define IFOE_TELEM_ID_NETPORT_TX_BAD_FCS 0x4000007
/* enum: Total number of good and bad 64-byte packets transmitted */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_64_BYTES 0x4000008
/* enum: Total number of good and bad packets between 65 and 127 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_65_127_BYTES 0x4000009
/* enum: Total number of good and bad packets between 128 and 255 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_128_255_BYTES 0x400000a
/* enum: Total number of good and bad packets between 256 and 511 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_256_511_BYTES 0x400000b
/* enum: Total number of good and bad packets between 512 and 1023 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_512_1023_BYTES 0x400000c
/* enum: Total number of good and bad packets between 1024 and 1518 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_1024_1518_BYTES 0x400000d
/* enum: Total number of good and bad packets between 1519 and 1522 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_1519_1522_BYTES 0x400000e
/* enum: Total number of good and bad packets between 1523 and 1548 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_1523_1548_BYTES 0x400000f
/* enum: Total number of good and bad packets between 1549 and 2047 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_1549_2047_BYTES 0x4000010
/* enum: Total number of good and bad packets between 2048 and 4095 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_2048_4095_BYTES 0x4000011
/* enum: Total number of good and bad packets between 4096 and 8191 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_4096_8191_BYTES 0x4000012
/* enum: Total number of good and bad packets between 8192 and 9215 bytes
 * transmitted
 */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_8192_9215_BYTES 0x4000013
/* enum: Total number of packets that are over 9215 bytes long */
#define IFOE_TELEM_ID_NETPORT_TX_PACKET_LARGE 0x4000014
/* enum: Total number of good unicast packets */
#define IFOE_TELEM_ID_NETPORT_TX_UNICAST 0x4000015
/* enum: Total number of good multicast packets */
#define IFOE_TELEM_ID_NETPORT_TX_MULTICAST 0x4000016
/* enum: Total number of good broadcast packets */
#define IFOE_TELEM_ID_NETPORT_TX_BROADCAST 0x4000017
/* enum: Total number of good 802.1Q tagged VLAN packets */
#define IFOE_TELEM_ID_NETPORT_TX_VLAN 0x4000018
/* enum: Total number of 802.3x MAC Pause packets with good FCS */
#define IFOE_TELEM_ID_NETPORT_TX_PAUSE 0x4000019
/* enum: Total number of priority based pause packets with good FCS */
#define IFOE_TELEM_ID_NETPORT_TX_USER_PAUSE 0x400001a
/* enum: Total number of padding bytes added to packets */
#define IFOE_TELEM_ID_NETPORT_TX_TOTAL_PAD_BYTES 0x400001b
/* enum: Total number of packets that were padded */
#define IFOE_TELEM_ID_NETPORT_TX_TOTAL_PAD_PACKETS 0x400001c
/* enum: Total number of bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_TOTAL_BYTES 0x4001001
/* enum: Total number of bytes received in good (error-free) packets */
#define IFOE_TELEM_ID_NETPORT_RX_TOTAL_GOOD_BYTES 0x4001002
/* enum: Total number of bytes received in bad (errored) packets */
#define IFOE_TELEM_ID_NETPORT_RX_TOTAL_ERR_BYTES 0x4001003
/* enum: Total number of packets received */
#define IFOE_TELEM_ID_NETPORT_RX_TOTAL_PACKETS 0x4001004
/* enum: Total number of good (error-free) packets received */
#define IFOE_TELEM_ID_NETPORT_RX_TOTAL_GOOD_PACKETS 0x4001005
/* enum: Total number of small (less than 64 bytes) packets received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_SMALL 0x4001006
/* enum: Total number of dropped packets */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_DROPPED 0x4001007
/* enum: Count of 64B/66B code violations observed in the MAC */
#define IFOE_TELEM_ID_NETPORT_RX_BAD_CODE_COUNT 0x4001008
/* enum: Total number of packets received with bad (but not stomped) FCS. A
 * stomped FCS is defined as the bitwise inverse of a good FCS.
 */
#define IFOE_TELEM_ID_NETPORT_RX_BAD_FCS 0x4001009
/* enum: Total number of packets between 64 and rx_max_packet_len bytes that
 * have FCS errors
 */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_BAD_FCS 0x400100a
/* enum: Total number of packets received with stomped FCS. A stomped FCS is
 * defined as the bitwise inverse of a good FCS.
 */
#define IFOE_TELEM_ID_NETPORT_RX_STOMPED_FCS 0x400100b
/* enum: Total number of frames that were truncated due to their length
 * exceeding the defined maximum length
 */
#define IFOE_TELEM_ID_NETPORT_RX_TRUNCATED 0x400100c
/* enum: Total number of 64 byte packets received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_64_BYTES 0x400100d
/* enum: Total number of packets between 65 and 127 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_65_127_BYTES 0x400100e
/* enum: Total number of packets between 128 and 255 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_128_255_BYTES 0x400100f
/* enum: Total number of packets between 256 and 511 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_256_511_BYTES 0x4001010
/* enum: Total number of packets between 512 and 1023 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_512_1023_BYTES 0x4001011
/* enum: Total number of packets between 1024 and 1518 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_1024_1518_BYTES 0x4001012
/* enum: Total number of packets between 1519 and 1522 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_1519_1522_BYTES 0x4001013
/* enum: Total number of packets between 1523 and 1548 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_1523_1548_BYTES 0x4001014
/* enum: Total number of packets between 1549 and 2047 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_1549_2047_BYTES 0x4001015
/* enum: Total number of packets between 2048 and 4095 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_2048_4095_BYTES 0x4001016
/* enum: Total number of packets between 4096 and 8191 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_4096_8191_BYTES 0x4001017
/* enum: Total number of packets between 8192 and 9215 bytes received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_8192_9215_BYTES 0x4001018
/* enum: Total number of packets longer than rx_max_packet_len with either good
 * or bad FCS
 */
#define IFOE_TELEM_ID_NETPORT_RX_TOOLONG 0x4001019
/* enum: Total number of large (greater than 9215 bytes) packets received */
#define IFOE_TELEM_ID_NETPORT_RX_PACKET_LARGE 0x400101a
/* enum: Total number of packets longer than rx_max_packet_len with bad FCS */
#define IFOE_TELEM_ID_NETPORT_RX_JABBER 0x400101b
/* enum: Total number of packets longer than rx_max_packet_len with good FCS */
#define IFOE_TELEM_ID_NETPORT_RX_OVERSIZE 0x400101c
/* enum: Total number of received unicast packets */
#define IFOE_TELEM_ID_NETPORT_RX_UNICAST 0x400101d
/* enum: Total number of received multicast packets */
#define IFOE_TELEM_ID_NETPORT_RX_MULTICAST 0x400101e
/* enum: Total number of received broadcast packets */
#define IFOE_TELEM_ID_NETPORT_RX_BROADCAST 0x400101f
/* enum: Total number of received VLAN-tagged packets */
#define IFOE_TELEM_ID_NETPORT_RX_VLAN 0x4001020
/* enum: Total number of received 802.3x Pause packets with good FCS */
#define IFOE_TELEM_ID_NETPORT_RX_PAUSE 0x4001021
/* enum: Total number of received priority-based pause packets with good FCS */
#define IFOE_TELEM_ID_NETPORT_RX_USER_PAUSE 0x4001022
/* enum: Total number of received frames with in-range length errors */
#define IFOE_TELEM_ID_NETPORT_RX_INRANGEERR 0x4001023
/* enum: Count of FEC processed codewords */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_CW 0x4002001
/* enum: Count of FEC corrected codewords */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_CORRECTED_CW 0x4002002
/* enum: Count of FEC uncorrected codewords */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_UNCORRECTED_CW 0x4002003
/* enum: Count of FEC codeword B for interleaved FEC modes */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_CWB 0x4002004
/* enum: Count of FEC corrected codeword B for interleaved FEC modes */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_CORRECTED_CWB 0x4002005
/* enum: Count of FEC uncorrected codeword B for interleaved FEC modes */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_UNCORRECTED_CWB 0x4002006
/* enum: Number of bits corrected from 0 to 1 by RX FEC on lane 0 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_BIT_ERR_0TO1_L0 0x4002007
/* enum: Number of bits corrected from 0 to 1 by RX FEC on lane 1 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_BIT_ERR_0TO1_L1 0x4002008
/* enum: Number of bits corrected from 0 to 1 by RX FEC on lane 2 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_BIT_ERR_0TO1_L2 0x4002009
/* enum: Number of bits corrected from 0 to 1 by RX FEC on lane 3 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_BIT_ERR_0TO1_L3 0x400200a
/* enum: Number of bits corrected from 1 to 0 by RX FEC on lane 0 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_BIT_ERR_1TO0_L0_LSB 0x400200b
/* enum: Number of bits corrected from 1 to 0 by RX FEC on lane 1 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_BIT_ERR_1TO0_L1_LSB 0x400200c
/* enum: Number of bits corrected from 1 to 0 by RX FEC on lane 2 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_BIT_ERR_1TO0_L2_LSB 0x400200d
/* enum: Number of bits corrected from 1 to 0 by RX FEC on lane 3 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_BIT_ERR_1TO0_L3_LSB 0x400200e
/* enum: Count of FEC symbol errors corrected on FEC lane 0 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_ERR_COUNT_L0_LSB 0x400200f
/* enum: Count of FEC symbol errors corrected on FEC lane 1 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_ERR_COUNT_L1_LSB 0x4002010
/* enum: Count of FEC symbol errors corrected on FEC lane 2 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_ERR_COUNT_L2_LSB 0x4002011
/* enum: Count of FEC symbol errors corrected on FEC lane 3 */
#define IFOE_TELEM_ID_NETPORT_RX_FEC_ERR_COUNT_L3_LSB 0x4002012
/* enum: The sequence number acknowledged in the most recent successfully
 * received LLR_ACK or LLR_NACK. Range of 0 to 1,048,575
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_ACKED_SEQ 0x4003001
/* enum: Live value of the timer which tracks how long packets have been
 * sitting in the replay buffer without any acknowledgement
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_DATA_AGE_TIMER 0x4003002
/* enum: Current value of the total amount of data (in bytes) for
 * unacknowledged frames
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_OUTSTANDING_DATA 0x4003003
/* enum: Live value of the number of unacknowledged frames that have been
 * transmitted. Range 0 to 524,288
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_OUTSTANDING_SEQ 0x4003004
/* enum: Live value of the timer which tracks how long PCS_Status is FALSE.
 * Units are pairs of tx_core_clk cycles.
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_PCS_LOST_STATUS_TIMER 0x4003005
/* enum: Live value of the counter which tracks how many replay operations have
 * been performed without receiving an LLR_ACK
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_REPLAY_CT 0x4003006
/* enum: Live value of the timer which tracks the number of tx_core_clk cycles
 * since receiving an LLR_ACK
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_REPLAY_TIMER 0x4003007
/* enum: Sequence number that will be used for the next transmitted LLR-
 * eligible frame. Range 0 to 1,048,575
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_TX_SEQ 0x4003008
/* enum: Latest round-trip latency estimate in ts_clk cycles. 0 indicates that
 * no round-trip estimate calculation has yet completed.
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_RTT_ESTIMATE 0x4003009
/* enum: Number of transmitted LLR_ACK CtlOS */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_ACK_CTLOS 0x400300a
/* enum: Number of transmitted LLR_NACK CtlOS */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_NACK_CTLOS 0x400300b
/* enum: Number of transmitted LLR_INIT CtlOS */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_INIT_CTLOS 0x400300c
/* enum: Number of transmitted LLR_INIT_ECHO CtlOS */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_INIT_ECHO_CTLOS 0x400300d
/* enum: Number of LLR_ACK/LLR_NACK CtlOS that contain a sequence number that
 * implies a sequence number error
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_RCVD_ACK_NACK_SEQ_ERROR 0x400300e
/* enum: Number of times the LLR TX FSM exited the REPLAY state */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_REPLAYS_COMPLETED 0x400300f
/* enum: Number of transmit frames discarded while the LLR TX is in the FLUSH
 * state
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_FLUSH_DISCARDED_PACKETS 0x4003010
/* enum: Number of transmit frames discarded while the LLR TX is in the INIT
 * state
 */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_INIT_DISCARDED_PACKETS 0x4003011
/* enum: Number of LLR-eligible frames transmitted with a good FCS */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_OK_PACKETS 0x4003012
/* enum: Number of LLR-eligible frames transmitted with a poisoned FCS */
#define IFOE_TELEM_ID_NETPORT_TX_LLR_POISONED_PACKETS 0x4003013
/* enum: Expected sequence number of the next LLR-eligible frame to be received
 */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_NEXT_RX_SEQ 0x4004001
/* enum: Number of received LLR_ACK CtlOS */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_ACK_CTLOS 0x4004002
/* enum: Number of received LLR_NACK CtlOS */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_NACK_CTLOS 0x4004003
/* enum: Number of received LLR_INIT CtlOS */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_INIT_CTLOS 0x4004004
/* enum: Number of received LLR_INIT_ECHO CtlOS */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_INIT_ECHO_CTLOS 0x4004005
/* enum: Number of times the RX detected the start of a replay */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_REPLAYS_DETECTED 0x4004006
/* enum: Number of LLR-eligible frames received with a bad FCS */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_BAD_PACKETS 0x4004007
/* enum: Number of LLR-eligible frames received with a sequence number
 * indicating that the frame has already been successfully received
 */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_DUPL_SEQ_PACKETS 0x4004008
/* enum: Number of LLR-eligible frames received with the expected sequence
 * number and with a bad FCS
 */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_EXP_SEQ_BAD_PACKETS 0x4004009
/* enum: Number of LLR-eligible frames received with the expected sequence
 * number and a good FCS
 */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_EXP_SEQ_GOOD_PACKETS 0x400400a
/* enum: Number of LLR-eligible frames received with the expected sequence
 * number and a poisoned FCS
 */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_EXP_SEQ_POISONED_PACKETS 0x400400b
/* enum: Number of LLR-eligible frames received with a sequence number
 * indicating that a frame has been lost
 */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_MISS_SEQ_PACKETS 0x400400c
/* enum: Number of LLR-eligible frames received with a good FCS */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_OK_PACKETS 0x400400d
/* enum: Number of LLR-eligible frames received with a poisoned FCS */
#define IFOE_TELEM_ID_NETPORT_RX_LLR_POISONED_PACKETS 0x400400e
/* enum: *** Telemetry IDs for the derived / SW constructed telemetry per-IFOE
 * station *** Bitmask of flags indicating the status of the IFoE logical link.
 * A value of 0 means the link is fully up with no issues detected. Refer to
 * IFOE_TELEM_LINK_STATUS for the definition of each flag.
 */
#define IFOE_TELEM_ID_IFOE_LOGICAL_LINK_STATUS 0x5000001
/* enum: Current bandwidth of IFoE logical link in Gbit/s. If the logical link
 * is degraded due to an issue with one of the underlying network ports this
 * bandwidth will be reduced.
 */
#define IFOE_TELEM_ID_IFOE_LOGICAL_LINK_BW 0x5000002
/* enum: Count of number of IFoE Request packets transmitted */
#define IFOE_TELEM_ID_IFOE_TX_REQUEST_PKT_COUNT 0x5000003
/* enum: Count of number of IFoE Response packets transmitted */
#define IFOE_TELEM_ID_IFOE_TX_RESPONSE_PKT_COUNT 0x5000004
/* enum: Count of number of IFoE Request packets received */
#define IFOE_TELEM_ID_IFOE_RX_REQUEST_PKT_COUNT 0x5000005
/* enum: Count of number of IFoE Response packets received */
#define IFOE_TELEM_ID_IFOE_RX_RESPONSE_PKT_COUNT 0x5000006
/* enum: Count of the total number of streams that have been remapped due to a
 * retransmission timeout.
 */
#define IFOE_TELEM_ID_IFOE_STREAM_REMAPS_TOTAL 0x5000007
/* enum: Count of the number of streams that have been remapped due to a
 * retransmission timeout on Network Port 0
 */
#define IFOE_TELEM_ID_IFOE_STREAM_REMAPS_NPORT_0 0x5000008
/* enum: Count of the number of streams that have been remapped due to a
 * retransmission timeout on Network Port 1
 */
#define IFOE_TELEM_ID_IFOE_STREAM_REMAPS_NPORT_1 0x5000009
/* enum: Count of the number of streams that have been remapped due to a
 * retransmission timeout on Network Port 2
 */
#define IFOE_TELEM_ID_IFOE_STREAM_REMAPS_NPORT_2 0x500000a
/* enum: Count of the number of streams that have been remapped due to a
 * retransmission timeout on Network Port 3
 */
#define IFOE_TELEM_ID_IFOE_STREAM_REMAPS_NPORT_3 0x500000b
/* enum: Live number of IFoE streams paused due to retransmission timeouts */
#define IFOE_TELEM_ID_IFOE_PAUSED_STREAMS_COUNT 0x500000c
/* enum: Count of the number of times the encryption key was updated for
 * Security Association 0.
 */
#define IFOE_TELEM_ID_IFOE_CRYPTO_TX_KEY_UPDATES_SA0 0x5001001
/* enum: Count of the number of times decryption key 0 was updated for Security
 * Association 0.
 */
#define IFOE_TELEM_ID_IFOE_CRYPTO_RX_KEY0_UPDATES_SA0 0x5001002
/* enum: Count of the number of times decryption key 1 was updated for Security
 * Association 0.
 */
#define IFOE_TELEM_ID_IFOE_CRYPTO_RX_KEY1_UPDATES_SA0 0x5001003
/* enum: Count of number of times a decryption key was disabled for Security
 * Association 0.
 */
#define IFOE_TELEM_ID_IFOE_CRYPTO_RX_KEY_DISABLES_SA0 0x5001004
/* enum: Count of the number of times the encryption key was updated for
 * Security Association 1.
 */
#define IFOE_TELEM_ID_IFOE_CRYPTO_TX_KEY_UPDATES_SA1 0x5002001
/* enum: Count of the number of times decryption key 0 was updated for Security
 * Association 1.
 */
#define IFOE_TELEM_ID_IFOE_CRYPTO_RX_KEY0_UPDATES_SA1 0x5002002
/* enum: Count of the number of times decryption key 1 was updated for Security
 * Association 1.
 */
#define IFOE_TELEM_ID_IFOE_CRYPTO_RX_KEY1_UPDATES_SA1 0x5002003
/* enum: Count of number of times a decryption key was disabled for Security
 * Association 0.
 */
#define IFOE_TELEM_ID_IFOE_CRYPTO_RX_KEY_DISABLES_SA1 0x5002004
/* enum: *** Telemetry IDs for the derived / SW constructed telemetry per
 * Network Port *** Bitmask of flags indicating the status of the Network Port.
 * A value of 0 means the link is fully up with no issues detected. Refer to
 * IFOE_TELEM_NETPORT_STATUS for the definition of each flag.
 */
#define IFOE_TELEM_ID_NETPORT_LINK_STATUS 0x6000001
/* enum: Indicates the auto-negotiated link speed in Gbits/s. Note that this
 * field can read a non-zero value even if the link is down.
 */
#define IFOE_TELEM_ID_NETPORT_LINK_SPEED 0x6000002
/* enum: Current Bit Error Rate reported by the network port expressed as
 * errors per 10^12 bits
 */
#define IFOE_TELEM_ID_NETPORT_BIT_ERROR_RATE 0x6000003
/* enum: Time taken to complete link training for most recent link up in ms */
#define IFOE_TELEM_ID_NETPORT_LAST_LINK_TRAINING_DURATION 0x6000004
/* enum: Average time taken to complete link training in ms */
#define IFOE_TELEM_ID_NETPORT_AVERAGE_LINK_TRAINING_TIME 0x6000005
/* enum: Number of times that the network link has come up */
#define IFOE_TELEM_ID_NETPORT_LINK_UP_COUNT 0x6000006
/* enum: Total time that the network link has been up in ms */
#define IFOE_TELEM_ID_NETPORT_LINK_UP_TIME 0x6000007
/* enum: Total time that the network link has been down in ms */
#define IFOE_TELEM_ID_NETPORT_LINK_DOWN_TIME 0x6000008
/* enum: Count of number of FEC codewords with no symbol errors. To support
 * creation of a FEC histogram, telemetry is provided of the number of symbol
 * errors in each codeword. The reported number of codewords are accumulated
 * values. Host could compare with previous readings to determine the number of
 * codewords with a given number of symbol errors during a time interval.
 */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_0 0x6001001
/* enum: Count of number of FEC codewords with 1 symbol error */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_1 0x6001002
/* enum: Count of number of FEC codewords with 2 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_2 0x6001003
/* enum: Count of number of FEC codewords with 3 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_3 0x6001004
/* enum: Count of number of FEC codewords with 4 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_4 0x6001005
/* enum: Count of number of FEC codewords with 5 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_5 0x6001006
/* enum: Count of number of FEC codewords with 6 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_6 0x6001007
/* enum: Count of number of FEC codewords with 7 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_7 0x6001008
/* enum: Count of number of FEC codewords with 8 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_8 0x6001009
/* enum: Count of number of FEC codewords with 9 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_9 0x600100a
/* enum: Count of number of FEC codewords with 10 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_10 0x600100b
/* enum: Count of number of FEC codewords with 11 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_11 0x600100c
/* enum: Count of number of FEC codewords with 12 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_12 0x600100d
/* enum: Count of number of FEC codewords with 13 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_13 0x600100e
/* enum: Count of number of FEC codewords with 14 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_14 0x600100f
/* enum: Count of number of FEC codewords with 15 symbol errors */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_15 0x6001010
/* enum: Count of number of FEC codewords with an uncorrectable number of
 * symbol errors (>15)
 */
#define IFOE_TELEM_ID_NETPORT_FEC_CW_SYMBOL_ERRS_UNCORRECTABLE 0x6001011
/* enum: Total count of packets that were received from the network but
 * silently dropped (by firmware). This is the sum of all drop counters below.
 */
#define IFOE_TELEM_ID_NETPORT_RX_DROP_TOTAL 0x6002001
/* enum: Count of packets dropped due to a mismatch between the destination MAC
 * address and the local accelerator MAC. Excluding broadcast or multicast
 * addresses.
 */
#define IFOE_TELEM_ID_NETPORT_RX_DROP_MAC_FILTERED 0x6002002
/* enum: Count of packets dropped due to no available host RX descriptor to
 * deliver the packet into.
 */
#define IFOE_TELEM_ID_NETPORT_RX_DROP_NO_DESCRIPTOR 0x6002003
/* enum: Count of packets dropped due to the DMA transfer of the packet to host
 * memory failing.
 */
#define IFOE_TELEM_ID_NETPORT_RX_DROP_DMA_ERROR 0x6002004
/* enum: Count of control packets (e.g. IFoE ping) dropped by firmware because
 * they were malformed, unaddressed to this accelerator or otherwise failed
 * validation.
 */
#define IFOE_TELEM_ID_NETPORT_RX_DROP_INVALID 0x6002005
/* enum: *** Telemetry IDs for the IFoE debug datapath *** Number of packets
 * queued by perfmon instance 0
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_PACKETS_QUEUED 0x7001001
/* enum: Number of packets sent by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_PACKETS_SENT 0x7001002
/* enum: Number of packets resent by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_PACKETS_RESENT 0x7001003
/* enum: Number of packets freed by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_PACKETS_FREED 0x7001004
/* enum: Number of granules queued by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_GRANULES_QUEUED 0x7001005
/* enum: Number of granules sent by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_GRANULES_SENT 0x7001006
/* enum: Number of granules resent by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_GRANULES_RESENT 0x7001007
/* enum: Number of granules freed by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_GRANULES_FREED 0x7001008
/* enum: Number of pure ACK packets sent by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_PACKETS_PURE_ACK 0x7001009
/* enum: Number of TXNAKs observed by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_TXNAKS 0x700100a
/* enum: Number of TXACK timer elapses observed by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_TXACK_ELAPSES 0x700100b
/* enum: Number of RXNAKs observed by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_RXNAKS 0x700100c
/* enum: Number of RXACK timer elapses observed by perfmon instance 0 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_RXACK_ELAPSES 0x700100d
/* enum: Mean number of packets in-flight measured by perfmon instance 0, in
 * fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_MEAN_PACKETS_INFLIGHT 0x700100e
/* enum: Mean number of granules in-flight measured by perfmon instance 0, in
 * fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_MEAN_GRANULES_INFLIGHT 0x700100f
/* enum: Mean send latency in cycles measured by perfmon instance 0, in fixed-
 * point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_MEAN_SEND_LATENCY 0x7001010
/* enum: Mean absolute deviation of send latency in cycles measured by perfmon
 * instance 0, in fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_MAD_SEND_LATENCY 0x7001011
/* enum: Mean free latency in cycles measured by perfmon instance 0, in fixed-
 * point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_MEAN_FREE_LATENCY 0x7001012
/* enum: Mean absolute deviation of free latency in cycles measured by perfmon
 * instance 0, in fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON0_MAD_FREE_LATENCY 0x7001013
/* enum: Number of packets queued by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_PACKETS_QUEUED 0x7002001
/* enum: Number of packets sent by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_PACKETS_SENT 0x7002002
/* enum: Number of packets resent by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_PACKETS_RESENT 0x7002003
/* enum: Number of packets freed by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_PACKETS_FREED 0x7002004
/* enum: Number of granules queued by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_GRANULES_QUEUED 0x7002005
/* enum: Number of granules sent by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_GRANULES_SENT 0x7002006
/* enum: Number of granules resent by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_GRANULES_RESENT 0x7002007
/* enum: Number of granules freed by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_GRANULES_FREED 0x7002008
/* enum: Number of pure ACK packets sent by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_PACKETS_PURE_ACK 0x7002009
/* enum: Number of TXNAKs observed by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_TXNAKS 0x700200a
/* enum: Number of TXACK timer elapses observed by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_TXACK_ELAPSES 0x700200b
/* enum: Number of RXNAKs observed by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_RXNAKS 0x700200c
/* enum: Number of RXACK timer elapses observed by perfmon instance 1 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_RXACK_ELAPSES 0x700200d
/* enum: Mean number of packets in-flight measured by perfmon instance 1, in
 * fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_MEAN_PACKETS_INFLIGHT 0x700200e
/* enum: Mean number of granules in-flight measured by perfmon instance 1, in
 * fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_MEAN_GRANULES_INFLIGHT 0x700200f
/* enum: Mean send latency in cycles measured by perfmon instance 1, in fixed-
 * point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_MEAN_SEND_LATENCY 0x7002010
/* enum: Mean absolute deviation of send latency in cycles measured by perfmon
 * instance 1, in fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_MAD_SEND_LATENCY 0x7002011
/* enum: Mean free latency in cycles measured by perfmon instance 1, in fixed-
 * point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_MEAN_FREE_LATENCY 0x7002012
/* enum: Mean absolute deviation of free latency in cycles measured by perfmon
 * instance 1, in fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON1_MAD_FREE_LATENCY 0x7002013
/* enum: Number of packets queued by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_PACKETS_QUEUED 0x7003001
/* enum: Number of packets sent by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_PACKETS_SENT 0x7003002
/* enum: Number of packets resent by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_PACKETS_RESENT 0x7003003
/* enum: Number of packets freed by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_PACKETS_FREED 0x7003004
/* enum: Number of granules queued by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_GRANULES_QUEUED 0x7003005
/* enum: Number of granules sent by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_GRANULES_SENT 0x7003006
/* enum: Number of granules resent by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_GRANULES_RESENT 0x7003007
/* enum: Number of granules freed by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_GRANULES_FREED 0x7003008
/* enum: Number of pure ACK packets sent by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_PACKETS_PURE_ACK 0x7003009
/* enum: Number of TXNAKs observed by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_TXNAKS 0x700300a
/* enum: Number of TXACK timer elapses observed by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_TXACK_ELAPSES 0x700300b
/* enum: Number of RXNAKs observed by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_RXNAKS 0x700300c
/* enum: Number of RXACK timer elapses observed by perfmon instance 2 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_RXACK_ELAPSES 0x700300d
/* enum: Mean number of packets in-flight measured by perfmon instance 2, in
 * fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_MEAN_PACKETS_INFLIGHT 0x700300e
/* enum: Mean number of granules in-flight measured by perfmon instance 2, in
 * fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_MEAN_GRANULES_INFLIGHT 0x700300f
/* enum: Mean send latency in cycles measured by perfmon instance 2, in fixed-
 * point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_MEAN_SEND_LATENCY 0x7003010
/* enum: Mean absolute deviation of send latency in cycles measured by perfmon
 * instance 2, in fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_MAD_SEND_LATENCY 0x7003011
/* enum: Mean free latency in cycles measured by perfmon instance 2, in fixed-
 * point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_MEAN_FREE_LATENCY 0x7003012
/* enum: Mean absolute deviation of free latency in cycles measured by perfmon
 * instance 2, in fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON2_MAD_FREE_LATENCY 0x7003013
/* enum: Number of packets queued by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_PACKETS_QUEUED 0x7004001
/* enum: Number of packets sent by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_PACKETS_SENT 0x7004002
/* enum: Number of packets resent by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_PACKETS_RESENT 0x7004003
/* enum: Number of packets freed by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_PACKETS_FREED 0x7004004
/* enum: Number of granules queued by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_GRANULES_QUEUED 0x7004005
/* enum: Number of granules sent by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_GRANULES_SENT 0x7004006
/* enum: Number of granules resent by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_GRANULES_RESENT 0x7004007
/* enum: Number of granules freed by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_GRANULES_FREED 0x7004008
/* enum: Number of pure ACK packets sent by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_PACKETS_PURE_ACK 0x7004009
/* enum: Number of TXNAKs observed by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_TXNAKS 0x700400a
/* enum: Number of TXACK timer elapses observed by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_TXACK_ELAPSES 0x700400b
/* enum: Number of RXNAKs observed by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_RXNAKS 0x700400c
/* enum: Number of RXACK timer elapses observed by perfmon instance 3 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_RXACK_ELAPSES 0x700400d
/* enum: Mean number of packets in-flight measured by perfmon instance 3, in
 * fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_MEAN_PACKETS_INFLIGHT 0x700400e
/* enum: Mean number of granules in-flight measured by perfmon instance 3, in
 * fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_MEAN_GRANULES_INFLIGHT 0x700400f
/* enum: Mean send latency in cycles measured by perfmon instance 3, in fixed-
 * point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_MEAN_SEND_LATENCY 0x7004010
/* enum: Mean absolute deviation of send latency in cycles measured by perfmon
 * instance 3, in fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_MAD_SEND_LATENCY 0x7004011
/* enum: Mean free latency in cycles measured by perfmon instance 3, in fixed-
 * point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_MEAN_FREE_LATENCY 0x7004012
/* enum: Mean absolute deviation of free latency in cycles measured by perfmon
 * instance 3, in fixed-point format with 8 fractional bits
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PERFMON3_MAD_FREE_LATENCY 0x7004013
/* enum: *** RX SOP error flags and SEEN counters *** Raw SOP error flags
 * register. Each bit corresponds to a sticky error condition detected at SOP.
 * Bit definitions match STA_RX_DECAP_SOP_ERROR_FLAGS in the hardware register
 * map.
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_SOP_ERROR_FLAGS 0x7005001
/* enum: Count of times firmware has observed the bad IPv4 protocol field
 * sticky bit set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_IPV4_PROTOCOL_SEEN 0x7005002
/* enum: Count of times firmware has observed the bad IPv4 IHL field sticky bit
 * set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_IPV4_IHL_SEEN 0x7005003
/* enum: Count of times firmware has observed the bad sequence number sticky
 * bit set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_SEQ_NUM_SEEN 0x7005004
/* enum: Count of times firmware has observed the bad destination address
 * sticky bit set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_DST_ADDR_SEEN 0x7005005
/* enum: Count of times firmware has observed the zero length payload with no
 * ACKs sticky bit set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_LEN_ZERO_NO_ACKS_SEEN 0x7005006
/* enum: Count of times firmware has observed the request packet carrying ACKs
 * sticky bit set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_REQ_HAS_ACKS_SEEN 0x7005007
/* enum: Count of times firmware has observed the packet length above threshold
 * sticky bit set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_LEN_ABOVE_THRESH_SEEN 0x7005008
/* enum: Count of times firmware has observed the bad destination ID sticky bit
 * set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_DEST_ID_SEEN 0x7005009
/* enum: Count of times firmware has observed the bad stream ID sticky bit set
 * at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_STRM_ID_SEEN 0x700500a
/* enum: Count of times firmware has observed the bad security status sticky
 * bit set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_SEC_SOP_STATUS_SEEN 0x700500b
/* enum: Count of times firmware has observed the bad VLAN ID sticky bit set at
 * SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_VID_SEEN 0x700500c
/* enum: Count of times firmware has observed the bad EtherType sticky bit set
 * at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_ETH_TYPE_SEEN 0x700500d
/* enum: Count of times firmware has observed the disabled stream ID sticky bit
 * set at SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_STRM_ID_DISABLED_SEEN 0x700500e
/* enum: Count of times firmware has observed the RX disabled sticky bit set at
 * SOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_RX_DISABLED_SEEN 0x700500f
/* enum: *** RX EOP error flags and SEEN counters *** Raw EOP error flags
 * register. Each bit corresponds to a sticky error condition detected at EOP.
 * Bit definitions match STA_RX_DECAP_EOP_ERROR_FLAGS in the hardware register
 * map.
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_EOP_ERROR_FLAGS 0x7006001
/* enum: Count of times firmware has observed the bad CRC sticky bit set at EOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_EOP_BAD_CRC_SEEN 0x7006002
/* enum: Count of times firmware has observed the bad EOP status sticky bit set
 * at EOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_EOP_BAD_EOP_STATUS_SEEN 0x7006003
/* enum: Count of times firmware has observed the EOP error flag sticky bit set
 * at EOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_EOP_ERROR_FLAG_SEEN 0x7006004
/* enum: Count of times firmware has observed the loss detection sticky bit set
 * at EOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_LOSS_DETECTION_SEEN 0x7006005
/* enum: Count of times firmware has observed the padding bytes error sticky
 * bit set at EOP
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_PADDING_BYTES_ERROR_SEEN 0x7006006
/* enum: Count of packets dropped due to configuration errors */
#define IFOE_TELEM_ID_IFOE_DEBUG_PKT_CFG_ERRORS 0x7007001
/* enum: Count of IFoE header errors detected */
#define IFOE_TELEM_ID_IFOE_DEBUG_IFOE_HDR_ERRORS 0x7007002
/* enum: Count of SOP security errors detected */
#define IFOE_TELEM_ID_IFOE_DEBUG_SOP_SEC_ERRORS 0x7007003
/* enum: Count of EOP security errors detected */
#define IFOE_TELEM_ID_IFOE_DEBUG_EOP_SEC_ERRORS 0x7007004
/* enum: Count of destination address errors detected */
#define IFOE_TELEM_ID_IFOE_DEBUG_DST_ADDR_ERRORS 0x7007005
/* enum: Count of sequence number errors detected */
#define IFOE_TELEM_ID_IFOE_DEBUG_SEQ_NUM_ERRORS 0x7007006
/* enum: Count of loss detection events reported */
#define IFOE_TELEM_ID_IFOE_DEBUG_LOSS_DETECTION_COUNT 0x7007007
/* enum: Count of CRC errors detected */
#define IFOE_TELEM_ID_IFOE_DEBUG_CRC_ERRORS 0x7007008
/* enum: *** Bad packet capture telemetry IDs *** Snapshot of the most recent
 * packet that latched one of the IFOE_DEBUG_SOP_ERROR_FLAGS /
 * IFOE_DEBUG_EOP_ERROR_FLAGS sticky bits above. Config error flag captured
 * from the most recent bad packet
 */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_CONFIG_ERROR 0x7008001
/* enum: Metadata fields captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_METADATA 0x7008002
/* enum: Ethernet header word 0 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_ETH_HDR_0 0x7008003
/* enum: Ethernet header word 1 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_ETH_HDR_1 0x7008004
/* enum: Ethernet header word 2 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_ETH_HDR_2 0x7008005
/* enum: Ethernet header word 3 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_ETH_HDR_3 0x7008006
/* enum: VLAN fields captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_VLAN 0x7008007
/* enum: IPv4 header word 0 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_IPV4_HDR_0 0x7008008
/* enum: IPv4 header word 1 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_IPV4_HDR_1 0x7008009
/* enum: IPv4 header word 2 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_IPV4_HDR_2 0x700800a
/* enum: IPv4 header word 3 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_IPV4_HDR_3 0x700800b
/* enum: IPv4 header word 4 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_IPV4_HDR_4 0x700800c
/* enum: IFoE header word 0 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_IFOE_HDR_0 0x700800d
/* enum: IFoE header word 1 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_IFOE_HDR_1 0x700800e
/* enum: IFoE header word 2 captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_IFOE_HDR_2 0x700800f
/* enum: ICV LSB captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_ICV_LSB 0x7008010
/* enum: ICV MSB captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_ICV_MSB 0x7008011
/* enum: CRC LSB captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_CRC_LSB 0x7008012
/* enum: CRC MSB captured from the most recent bad packet */
#define IFOE_TELEM_ID_IFOE_DEBUG_BAD_PKT_CRC_MSB 0x7008013
/* enum: Sticky bit set when a TX configuration error is detected */
#define IFOE_TELEM_ID_IFOE_DEBUG_TX_CONFIG_ERROR 0x7009001
/* enum: Count of TX packet headers generated */
#define IFOE_TELEM_ID_IFOE_DEBUG_TX_HDR 0x7009002
/* enum: Count of TX packet CRCs generated */
#define IFOE_TELEM_ID_IFOE_DEBUG_TX_CRC 0x7009003
/* enum: TX differential amplitude control (txdiffctrl_sa) */
#define IFOE_TELEM_ID_PHY_TXDIFFCTRL_SA 0x8000001
/* enum: TX pre-emphasis pre-cursor tap 1 (txemppre_sa) */
#define IFOE_TELEM_ID_PHY_TXEMPPRE_SA 0x8000002
/* enum: TX main cursor amplitude (txempmain_sa) */
#define IFOE_TELEM_ID_PHY_TXEMPMAIN_SA 0x8000003
/* enum: TX post-cursor tap amplitude (txemppos_sa) */
#define IFOE_TELEM_ID_PHY_TXEMPPOS_SA 0x8000004
/* enum: TX pre-emphasis pre-cursor tap 2 (txemppre2_sa) */
#define IFOE_TELEM_ID_PHY_TXEMPPRE2_SA 0x8000005
/* enum: TX pre-emphasis pre-cursor tap 3 (txemppre3_sa) */
#define IFOE_TELEM_ID_PHY_TXEMPPRE3_SA 0x8000006
/* enum: RX FFE pre-tap 8 (hm08_dac) */
#define IFOE_TELEM_ID_PHY_FFE_PRE_TAP_08_DAC 0x8000007
/* enum: RX FFE pre-tap 7 (hm07_dac) */
#define IFOE_TELEM_ID_PHY_FFE_PRE_TAP_07_DAC 0x8000008
/* enum: RX FFE pre-tap 6 (hm06_dac) */
#define IFOE_TELEM_ID_PHY_FFE_PRE_TAP_06_DAC 0x8000009
/* enum: RX FFE pre-tap 5 (hm05_dac) */
#define IFOE_TELEM_ID_PHY_FFE_PRE_TAP_05_DAC 0x800000a
/* enum: RX FFE pre-tap 4 (hm04_dac) */
#define IFOE_TELEM_ID_PHY_FFE_PRE_TAP_04_DAC 0x800000b
/* enum: RX FFE pre-tap 3 (hm03_dac) */
#define IFOE_TELEM_ID_PHY_FFE_PRE_TAP_03_DAC 0x800000c
/* enum: RX FFE pre-tap 2 (hm02_dac) */
#define IFOE_TELEM_ID_PHY_FFE_PRE_TAP_02_DAC 0x800000d
/* enum: RX FFE pre-tap 1 (hm01_dac) */
#define IFOE_TELEM_ID_PHY_FFE_PRE_TAP_01_DAC 0x800000e
/* enum: RX DFE H1 DAC value */
#define IFOE_TELEM_ID_PHY_H1_DAC 0x800000f
/* enum: RX FFE post-tap 1 (hp01_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_01_DAC 0x8000010
/* enum: RX FFE post-tap 2 (hp02_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_02_DAC 0x8000011
/* enum: RX FFE post-tap 3 (hp03_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_03_DAC 0x8000012
/* enum: RX FFE post-tap 4 (hp04_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_04_DAC 0x8000013
/* enum: RX FFE post-tap 5 (hp05_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_05_DAC 0x8000014
/* enum: RX FFE post-tap 6 (hp06_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_06_DAC 0x8000015
/* enum: RX FFE post-tap 7 (hp07_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_07_DAC 0x8000016
/* enum: RX FFE post-tap 8 (hp08_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_08_DAC 0x8000017
/* enum: RX FFE post-tap 9 (hp09_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_09_DAC 0x8000018
/* enum: RX FFE post-tap 10 (hp10_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_10_DAC 0x8000019
/* enum: RX FFE post-tap 11 (hp11_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_11_DAC 0x800001a
/* enum: RX FFE post-tap 12 (hp12_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_12_DAC 0x800001b
/* enum: RX FFE post-tap 13 (hp13_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_13_DAC 0x800001c
/* enum: RX FFE post-tap 14 (hp14_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_14_DAC 0x800001d
/* enum: RX FFE post-tap 15 (hp15_dac) */
#define IFOE_TELEM_ID_PHY_FFE_POST_TAP_15_DAC 0x800001e
/* enum: RX FFE floating tap 1 (hf01_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_01_DAC 0x800001f
/* enum: RX FFE floating tap 2 (hf02_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_02_DAC 0x8000020
/* enum: RX FFE floating tap 3 (hf03_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_03_DAC 0x8000021
/* enum: RX FFE floating tap 4 (hf04_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_04_DAC 0x8000022
/* enum: RX FFE floating tap 5 (hf05_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_05_DAC 0x8000023
/* enum: RX FFE floating tap 6 (hf06_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_06_DAC 0x8000024
/* enum: RX FFE floating tap 7 (hf07_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_07_DAC 0x8000025
/* enum: RX FFE floating tap 8 (hf08_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_08_DAC 0x8000026
/* enum: RX FFE floating tap 9 (hf09_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_09_DAC 0x8000027
/* enum: RX FFE floating tap 10 (hf10_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_10_DAC 0x8000028
/* enum: RX FFE floating tap 11 (hf11_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_11_DAC 0x8000029
/* enum: RX FFE floating tap 12 (hf12_dac) */
#define IFOE_TELEM_ID_PHY_FFE_FLOAT_TAP_12_DAC 0x800002a
/* enum: RX CTLE low-frequency peak (kl_dac) */
#define IFOE_TELEM_ID_PHY_LO_PEAK 0x800002b
/* enum: RX CTLE high-frequency peak (kh_dac) */
#define IFOE_TELEM_ID_PHY_HI_PEAK 0x800002c
/* enum: RX CTLE automatic gain control (agc_dac) */
#define IFOE_TELEM_ID_PHY_GC_DAC 0x800002d
#define IFOE_TELEM_ID_ID_LBN 0
#define IFOE_TELEM_ID_ID_WIDTH 64
