# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT
#
# This file provides configuration options for the Amd CUID Daemon.
#
# Each line should be in the format: key=value
daemonize=true
#     If true, the daemon will only become active when a new udev event which matches a supported device occurs.
#     If false, the daemon will run as a chron job at boot and periodically check for device changes.
logging=false
#     If true, the daemon will log its operations to syslog.
